### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by faxinwang** [modern-js-dev/modern.js#1105]
### 版本信息

```sh
无
```

### 问题详情

创建项目的命令运行报错
![image](https://user-images.githubusercontent.com/30144486/169660169-35d87d1b-2249-491b-992a-99771dc92261.png)

环境信息：
windows 10
node: v16.13.0
npm: v8.1.0

### 复现链接

无

### 复现步骤

无

**Comment by caohuilin** [comment]
@faxinwang 执行一下 `npx clear-npx-cache` 清除一下本地的 npx 缓存，在 npm8 的场景下 npx 不会拉最新的 @modern-js/create 的包

**Comment by chenjiahan** [comment]
@caohuilin 这个问题还挺常见的，今天也有其他同学反馈。感觉可以把文档里的 `npx @modern-js/create` 都改成 `npx clear-npx-cache && npx @modern-js/create`

**Comment by caohuilin** [comment]
> @caohuilin 这个问题还挺常见的，今天也有其他同学反馈。感觉可以把文档里的 `npx @modern-js/create` 都改成 `npx clear-npx-cache && npx @modern-js/create`

@chenjiahan 不能每次都清除 npx 缓存，这样能使用缓存的场景会影响加载速度，我在考虑后面如何做到尽可能的不更新 @modern-js/create 的内容，将逻辑都放到动态加载的生成器包中，这样能减少 @modern-js/create 的更新

**Comment by faxinwang** [comment]
执行了`npx clear-npx-cache`后再执行`npx @modern-js/create`, 会报如下新的错误：

⠋ Loading...(node:6004) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS 
requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)

⠇ Loading...[ERROR] load remote generator failed: Package @modern-js/repo-generator could not be found or get timeout
[ERROR] run task error: Error: load generator failed
    at GeneratorCore.runGenerator (E:\Software\installed\nvm\node_global_npm\node_modules\@modern-js\create\dist\js\node\main.js:304:13)
    at async CodeSmith.runTask (E:\Software\installed\nvm\node_global_npm\node_modules\@modern-js\create\dist\js\node\main.js:75:5)   
    at async CodeSmith.forge (E:\Software\installed\nvm\node_global_npm\node_modules\@modern-js\create\dist\js\node\main.js:58:9)     
    at async Command.createAction (E:\Software\installed\nvm\node_global_npm\node_modules\@modern-js\create\dist\js\node\main.js:218085:5)

**Comment by caohuilin** [comment]
> Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS

警告信息可以通过设置环境变量修复，可以参考： https://stackoverflow.com/questions/65021836/node26972-warning-setting-the-node-tls-reject-unauthorized-environment-varia
@modern-js/repo-generator  获取不到可以尝试使用设置本地 npm registry 为 cnpm
