### ISSUE TITLE
[Bug]: 严格来说不是个bug，关于modern start 自动给所有资源请求头加上Access-Control-Allow-Origin * 

### ISSUE THREAD

**Issue by nightmareT** [modern-js-dev/modern.js#1180]
### 版本信息

```sh
@elt/znhb@0.1.0 /Users/bytedance/bytedance/repos/page-maker-monorepo/apps/znhb
└── @modern-js/app-tools@1.4.0  -> /Users/bytedance/bytedance/repos/page-maker-monorepo/common/temp/node_modules/.pnpm/@modern-js+app-tools@1.4.0_typescript@4.5.5/node_modules/@modern-js/app-tools
```

### 问题详情

![image](https://user-images.githubusercontent.com/11377022/172803973-4509fbd3-521c-4de6-a0b4-246c2157a7db.png)

modern会自动的给静态文件的返回增加一个Access-Control-Allow-Origin * ，但实际这个是没有必要的，而且我们公司内部的安全要求不允许，想要禁用掉找不到对应的配置，所以希望能够有一个禁用的方法

### 复现链接

无需复现

### 复现步骤

任意项目modern start访问即可

**Comment by zllkjc** [comment]
这个已经删除了
