### ISSUE TITLE
[Bug]: @types/styled-components 的 5.1.25 版本将 react 的 type 升级到了 18，导致原有代码无法通过编译

### ISSUE THREAD

**Issue by nervouself** [modern-js-dev/modern.js#1270]
### 版本信息

```sh
"@modern-js/runtime": "1.3.2",
"@modern-js/runtime-core": "1.5.1",
"@modern-js/app-tools": "1.6.6",
```

### 问题详情

packages/runtime 引用了 @types/styled-components

@types/styled-components 的 5.1.25 版本将 react 的 type 升级到了 18，导致原有代码无法通过编译

@types/styled-components 的改动可见：
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/55dc209ceb6dbcd59c4c68cc8dfb77faadd9de12

### 复现链接

更新安装，让 @types/styled-components 为 5.1.25 即可

### 复现步骤

更新安装，让 @types/styled-components 为 5.1.25 即可

**Comment by chenjiahan** [comment]
可以先通过 yarn resolutions 或 pnpm overrides 锁一下 @types/react 的版本，我们后续看下怎么处理

**Comment by chenjiahan** [comment]
试了下，@types/styled-components >= 5.0.0 都有此问题，目前来说， resolutions 是最合适的解决方法。

@types/styled-components 的问题需要等待社区去解决了。相关 issue：https://github.com/DefinitelyTyped/DefinitelyTyped/issues/59765

![image](https://user-images.githubusercontent.com/7237365/175865124-722956fc-9995-46fc-91a1-50862b7b9463.png)
