### ISSUE TITLE
[Bug]: monorepo中minor patch， bump后major版本+1

### ISSUE THREAD

**Issue by CaanDoll** [modern-js-dev/modern.js#1318]
### Version

```sh
@modern-js/monorepo-tools@1.4.7
```

### Details

monorepo仓库中，A依赖B，B都进行minor patch，A进行patch。
希望情况是A与B minor版本+1。
实际情况是B minor版本+1，A major版本+1。

### Reproduce link

无

### Reproduce Steps

无

**Comment by caohuilin** [comment]
B 是 A 的 peerDependencies 依赖？这个是 changesets 的默认行为，可以加一下这个配置：
```
{
  "___experimentalUnsafeOptions_WILL_CHANGE_IN_PATCH": {
    "onlyUpdatePeerDependentsWhenOutOfRange": true
  }
}
```

**Comment by CaanDoll** [comment]
> B 是 A 的 peerDependencies 依赖？这个是 changesets 的默认行为，可以加一下这个配置：
> 
> ```
> {
>   "___experimentalUnsafeOptions_WILL_CHANGE_IN_PATCH": {
>     "onlyUpdatePeerDependentsWhenOutOfRange": true
>   }
> }
> ```

changeset config 加了这个配置也不行。。

**Comment by caohuilin** [comment]
@CaanDoll  提供一个复现项目路径和复现方式吧

**Comment by chenjiahan** [comment]
长时间无响应的 issue 将被关闭哈，如果需要支持可以重新打开。
