### ISSUE TITLE
[Bug]: 使用bff的时候无法热更新 必须重新run dev

### ISSUE THREAD

**Issue by lixudong96** [modern-js-dev/modern.js#1376]
### 版本信息

```sh
express-demo@0.1.0 /Users/lixudong/Development/bff-test/apps/express-demo

devDependencies:
@modern-js/app-tools 1.7.0
```

### 问题详情

使用bff无法热更新 必须重新run dev

### 复现链接

https://github.com/lixudong96/modern-bff-test

### 复现步骤

1. clone demo仓库
2. pnpm install 依赖
3. pnpm run dev --filter express-demo
4. 打开`expres-demo`下的api/lambda/login.ts
5. 随意修改post方法, 修改后点击按钮不会生效

**Comment by yimingjfe** [comment]
问题复现了，有  app.ts 的时候会导致热更新失败，下周四发版会修复的。

**Comment by lixudong96** [comment]
> 问题复现了，有 app.ts 的时候会导致热更新失败，下周四发版会修复的。

是api文件下的app.ts影响的吗, 请问下如果这段时间想热更应该怎么简单处理下好, 这几天需要对接接口
