### ISSUE TITLE
[Bug]: PreRender不生效，麻烦看下错在了哪个环节

### ISSUE THREAD

**Issue by crixusshen** [modern-js-dev/modern.js#1380]
### 版本信息

```sh
hello-fastman4@0.1.0 /Users/dfzq/modern-test
└── @modern-js/app-tools@1.6.10  -> /Users/dfzq/modern-test/node_modules/.pnpm/@modern-js+app-tools@1.6.10_c9c9c4f27a142d183a7a609b21611aec/node_modules/@modern-js/app-tools
```

### 问题详情

打算在公司大项目中运用，但是遇到了如下的问题（可能并不是bug，是使用问题），麻烦技术大佬看下🙏🏻🙏🏻🙏🏻：

在BFF层将接口（api/contacts.ts）故意延时2秒，然后在容器组件（src/contacts/containers/Contacts.ts）中使用了useLoader来调用这个api，目的是想对这个loader进行SSR + 服务端预渲染（PreRender），根据官方教程在入口文件（src/contacts/App.tsx）中使用了PreRender，过期时间为20秒。

预期效果：第一次访问 http://localhost:8080/contacts 应该会延迟2秒看到整个SSR页面，然后再次刷新会秒开且数据无变化，过了20秒之后再次刷新该页面，该页面同样可以秒开但数据会更新。

实际效果：第一次访问 http://localhost:8080/contacts 会延迟2秒看到整个SSR页面，然后再次刷新还是延时了2秒打开且数据更新，过了20秒之后再次刷新该页面，该页面仍然延时2秒打开且数据变化。

不知道是哪里错了，由于 PreRender 是一个比较重要的提升性能的利器特性，官方文档针对这块描述的比较简单，希望可以加强这块的文档使用，同时麻烦技术大佬帮我看下我这个demo中具体错在了哪里导致PreRender不生效🙏🏻🙏🏻🙏🏻！

### 复现链接

https://github.com/crixusshen/modern-test

### 复现步骤

1. 下载复现链接中的demo（这个demo基本就是官方的教程demo，只是我做了简化）后cd到根目录，执行：pnpm i  安装依赖；
2. 安装依赖后执行：pnpm run build && pnpm run start；
3. 访问 http://localhost:8080/contacts， 查看实际效果。

**Comment by zllkjc** [comment]
"pnpm": {
    "overrides": {
      "@modern-js/runtime": "0.0.0-alpha.202207172130"
    }
  },

**Comment by zllkjc** [comment]
是个 bug，修复了一下，可以先用这个版本工作看看。
```
"pnpm": {
    "overrides": {
      "@modern-js/runtime": "0.0.0-alpha.202207172130"
    }
  },
```

#1381

**Comment by crixusshen** [comment]
> 是个 bug，修复了一下，可以先用这个版本工作看看。
> 
> ```
> "pnpm": {
>     "overrides": {
>       "@modern-js/runtime": "0.0.0-alpha.202207172130"
>     }
>   },
> ```
> 
> #1381

该问题困扰了我一个周末，亲测可用，谢谢啦，希望可以在下一个版本加入修复👍🏻
