### ISSUE TITLE
[Bug]: 修改 jsPath、cssPath 后 start 启动访问 404

### ISSUE THREAD

**Issue by nervouself** [modern-js-dev/modern.js#1390]
### 版本信息

```sh
app-tools@1.7.0
```

### 问题详情

修改 jsPath、cssPath 后 start 启动访问 404
![image](https://user-images.githubusercontent.com/19755596/179933025-96544539-8022-4795-8fd5-9f516da50d9d.png)

### 复现链接

见复现步骤

### 复现步骤

npx @modern-js/create hello-modern

yarn new 启用 bff

修改
  jsPath: `./js-assets`,
  cssPath: `./css-assets`,
  mediaPath: `./media-assets`,

yarn build && yarn start 访问，静态资源 404

**Comment by chenjiahan** [comment]
get，我们排查下

**Comment by chenjiahan** [comment]
@zllkjc cc~ 看起来是 server 对 static 的处理有问题

**Comment by zllkjc** [comment]
这个问题已经修复了哈
