### ISSUE TITLE
[Bug]: ssrByEntries配置报错

### ISSUE THREAD

**Issue by crixusshen** [modern-js-dev/modern.js#1399]
### 版本信息

```sh
└── @modern-js/app-tools@1.7.0 -> ./node_modules/.pnpm/@modern-js+app-tools@1.7.0_c9c9c4f27a142d183a7a609b21611aec/node_modules/@modern-js/app-tools
```

### 问题详情

更新最新版本1.6.4后，如果modern.config.ts中配置了server.ssrByEntries，会报如下的错误信息，之前的版本是好的：

![image](https://user-images.githubusercontent.com/11752878/180709836-5eecd7c0-b03b-47ac-bee0-4b43b422f7d9.png)

### 复现链接

https://github.com/crixusshen/modern-bug.git

### 复现步骤

1. pnpm i
2. 打开 modern.config.ts 中 ssrByEntries 部分的注释
3. pnpm run dev

**Comment by zllkjc** [comment]
开启 SSR 的时候会进行 SSR Bundles 构建，但是你只有一个入口，又关闭了 SSR，所以导致没有 SSR Bundles 的入口了。
