### ISSUE TITLE
[Bug]: 关于bff部分使用遇到的问题

### ISSUE THREAD

**Issue by TayeShi** [modern-js-dev/modern.js#1433]
### 版本信息

```sh
gm-web-service-modern@0.1.0 C:\Work\ccz_svn_project\branches\dev\server\service\gm-web-service-modern
└── @modern-js/app-tools@1.8.0 -> .\node_modules\.pnpm\@modern-js+app-tools@1.8.0_typescript@4.7.4\node_modules\@modern-js\app-tools
```

### 问题详情

使用function方式koa
问题1：
![image](https://user-images.githubusercontent.com/22372742/181905639-5bac6563-b878-41d3-9d62-5cacdbf23777.png)
① 这个模块里没有导出match，这块到底该怎么用
② 文档啊，用心点。

问题2：
在modern.config.ts中开启bff proxy后。比如：`pathRewrite: { '^/api': '' },`，请求再也走不到自己写的bff函数中。（明明页面调用的就是自己写的bff方法，直接连这个也给转发了？）

另外：
使用eggjs的时候，启动过程中有异常。

ps: 其他使用过程中遇到问题还是小多。有点心累 - -！

### 复现链接

none

### 复现步骤

懒，不想提供demo。
顺着文档操作步骤操作一下就是了

**Comment by yimingjfe** [comment]
问题1是因为  match 我们不推荐使用了，内部版本有新的方式，待内部实践成熟后，会在开源版本中提供，这块因为之前没有项目使用，文档和相关代码都已经删除了，但文档看起来没更新成功，下周一会重新发布。

问题2这是因为 BFF 路由默认都有一个 [prefix](https://modernjs.dev/docs/apis/config/bff/prefix)，只有路径有这个前缀的请求才会经过 BFF Handler(Proxy)。

其他使用上的问题可以通过飞书沟通看一下具体的原因，飞书二维码见下，亦或者你提供联系方式也可：

![image](https://user-images.githubusercontent.com/10381581/182027268-612839c5-9a91-4512-ac0c-87f982adfef0.png)

谢谢反馈！
