### ISSUE TITLE
[Bug]: 飞书群无法进入

### ISSUE THREAD

**Issue by faxinwang** [modern-js-dev/modern.js#1683]
### 版本信息

```sh
无
```

### 问题详情

由于邀请人已经退出飞书群，官网的飞书群无法进入。

### 复现链接

无

### 复现步骤

无

**Comment by chenjiahan** [comment]
具体是哪个位置的链接~

**Comment by faxinwang** [comment]
就是官网首页底部> 关注我们> 飞书二维码 ，用手机扫码显示  无法加入，邀请人已经退出该群

**Comment by chenjiahan** [comment]
好滴，我们更新下

**Comment by chenjiahan** [comment]
今天会重新部署下官网，临时可以使用这个链接进群 https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=b02kf5fa-67d1-4abd-97c9-116cf1244185

**Comment by xmsz** [comment]
现在还可以进群吗

**Comment by chenjiahan** [comment]
可以从这个链接进：

https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=380rc1c0-056a-412d-ba53-5997e81af0e5

**Comment by xmsz** [comment]
> 今天会重新部署下官网，临时可以使用这个链接进群 https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=b02kf5fa-67d1-4abd-97c9-116cf1244185

提示群人数超过上限了

**Comment by chenjiahan** [comment]
噢噢，那就没法进群了😂 有问题直接在 GitHub issues 或讨论区聊吧~
