### ISSUE TITLE
[Bug]: @modern-js/plugin-electron 没有统一版本号

### ISSUE THREAD

**Issue by faxinwang** [modern-js-dev/modern.js#1684]
### 版本信息

```sh
无
```

### 问题详情

@modern-js/plugin-electron 这个插件没有统一版本号，导致electron项目无法将@modern-js下的依赖升级到最新版本。

### 复现链接

无

### 复现步骤

无

**Comment by chenjiahan** [comment]
@modern-js/plugin-electron 是在单独的仓库下面的，所以没有统一版本号哈。 

不过 @modern-js/plugin-electron 没有锁定底层依赖的版本，你通过 `pnpm update @modern-js/plugin-electron` 应该能升级上来。

**Comment by faxinwang** [comment]
嗷嗷，所以是对于pnpm管理依赖的项目，需要先锁定`@modern-js/plugin-electron`的版本号，在使用 `pnpm update "@modern-js/*" -r` 命令升级@modern-js/ 下面的其他依赖是吧？

**Comment by chenjiahan** [comment]
@modern-js/plugin-electron 不锁定也没事，一起升级就好

**Comment by faxinwang** [comment]
之前就是直接运行 `pnpm update "@modern-js/*" -r` 这个命令一起升级，会报错说@modern-js/plugin-electron 没有对应的版本号，我才过来提issue的。

**Comment by chenjiahan** [comment]
咦，应该不会升级到不存在的版本上，能截图看下吗

**Comment by faxinwang** [comment]
试了一下，确实可以这样。是我记错了，之前是使用`npx modern upgrade` 命令升级的时候，会报上面说的那个错误。

**Comment by chenjiahan** [comment]
@caohuilin 康康 modern upgrade 是不是要对 plugin-electron 处理下~
