### ISSUE TITLE
[RFC]: 有方法可以，做静态网页的部署。

### ISSUE THREAD

**Issue by vivide2333** [modern-js-dev/modern.js#1687]
### 这个功能解决了什么问题？

我们公司的项目，前端不需要用到后端的功能，只想要web的静态资源的产物，配合nginx使用。现在的部署方式，每次增加一个项目就要多一个web server。用多入口的方式的话，增加了新入口，但是部署的时候会影响老入口的部署。

### 你期望的 API 是什么样子的？

pnpm run build --static

**Comment by xuchaobei** [comment]
执行 pnpm run build ，产物已经是静态资源了，不依赖 web server 的，可以直接把这些静态资源部署到 nginx 上。
