### ISSUE TITLE
[Bug]: .env 自定义环境变量无效

### ISSUE THREAD

**Issue by GuoYiJi** [modern-js-dev/modern.js#1698]
### 版本信息

```sh
@modern-js/app-tools 1.18.0
```

### 问题详情

自定义的 env 变量，无法在代码里面获取
![image](https://user-images.githubusercontent.com/13943322/190297169-5f5047e1-a573-4f6f-920c-aa4bfb0b1983.png)

![image](https://user-images.githubusercontent.com/13943322/190297330-806fbd5f-539f-4a80-bc63-1a59a4080b14.png)

![image](https://user-images.githubusercontent.com/13943322/190297314-4de6de41-8f6e-46e7-823e-cf2ac5a5c744.png)

### 复现链接

-

### 复现步骤

pnpm dev

**Comment by chenjiahan** [comment]
默认情况下，.env 的环境变量是注入到 Server 端代码里的，如果要在 Client 端使用，还需要配置一下 source.envVars 参数哈

https://modernjs.dev/docs/apis/app/config/source/env-vars

**Comment by GuoYiJi** [comment]
谢谢，可以了
