### ISSUE TITLE
[Bug]: modern.config.ts 中的 electron.babel 配置项为函数形式时没有被调用

### ISSUE THREAD

**Issue by faxinwang** [modern-js-dev/modern.js#1803]
### 版本信息

```sh
test-electron@0.1.0 D:\projects\test-electron-modern
├── @modern-js/app-tools@1.19.0 -> .\node_modules\.pnpm\@modern-js+app-tools@1.19.0_kj4jjlrxxnopboqrxiwddbesd4\node_modules\@modern-js\app-tools        
└─┬ @modern-js/plugin-electron@1.0.19 -> .\node_modules\.pnpm\@modern-js+plugin-electron@1.0.19_36lybnqz6drtsltid3wcpjusc4\node_modules\@modern-js\plugin-electron
  └── @modern-js/app-tools@1.19.0 -> .\node_modules\.pnpm\@modern-js+app-tools@1.19.0_kj4jjlrxxnopboqrxiwddbesd4\node_modules\@modern-js\app-tools
```

### 问题详情

为了在electron项目的住进程和渲染进程中共享代码，按照官网的教程https://modernjs.dev/docs/guides/features/electron/extra/compile-extra 配置了 `share` 目录, 发现没有生效。于是在编写配置的地方，也就是 modern.config.ts 下面的 electron.babel 函数形式的选项中，使用console.log("test")，测试该函数是否有执行，发现该函数并没有执行。

之前配置 electron.build选项好像也没有生效，推测这两个选项好像都没有被处理。

### 复现链接

无

### 复现步骤

创建一个electron项目，按照 https://modernjs.dev/docs/guides/features/electron/extra/compile-extra  配置 share 目录，在 electron.babel 函数选项中使用 console.log("test") 测试函数是否有被执行。

**Comment by chenjiahan** [comment]
由于 Modern.js 整体规划调整，从 Modern.js 2.0 版本开始，将不再提供 Electron 工程方案，且 Modern.js v1 的 Electron 工程方案也不再进行新的迭代。

因此，Electron 相关 issue 将被关闭。如果有相关需求，欢迎 fork Modern.js Electron 相关代码进行二次开发，感谢理解~
