### ISSUE TITLE
[Bug]: 启用「Electron」模式，报错 '@modern-js/plugin-electron@1.20.1' is not in this registry.

### ISSUE THREAD

**Issue by asoiso** [modern-js-dev/modern.js#1894]
### 版本信息

```sh
dependencies:
@modern-js/runtime 1.20.1
react 17.0.2
react-dom 17.0.2

devDependencies:
@modern-js/app-tools 1.20.1
@modern-js/plugin-less 1.20.1
@modern-js/tsconfig 1.20.1
@types/node 14.18.32
@types/react 17.0.50
@types/react-dom 17.0.17
typescript 4.8.4
```

### 问题详情

error   Error: Command failed with exit code 1: npm view @modern-js/plugin-electron@1.20.1 version
npm ERR! code E404
npm ERR! 404 No match found for version 1.20.1
npm ERR! 404 
npm ERR! 404  '@modern-js/plugin-electron@1.20.1' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

### 复现链接

无

### 复现步骤

1、npx @modern-js/create website
? 请选择你想创建的工程类型： 应用
? 请选择开发语言： TS
? 请选择包管理工具： pnpm
? 是否需要支持以下类型应用： 不需要
? 是否需要调整默认配置：否
2、pnpm new
? 请选择你想要的操作 启用可选功能
? 启用可选功能：启用「Electron」模式

**Comment by caohuilin** [comment]
@asoiso 你可以先手动安装一下 @modern-js/plugin-electron 依赖，这个问题下个版本会修复
