### ISSUE TITLE
建议@modern-js/create创建的module添加files

### ISSUE THREAD

**Issue by yuki070** [modern-js-dev/modern.js#198]
根据文档 [开发工具库](https://modernjs.dev/docs/start/library)、[开发UI组件](https://modernjs.dev/docs/start/component) 生成的module中，package.json文件里缺少files的定义。

建议默认往package.json中添加files的配置，如：
```
"files": [
    "dist"
]
```

这样build出来的包在使用者那里的IDE里能正确识别到types和源码等文件。

**Comment by caohuilin** [comment]
https://github.com/modern-js-dev/modern.js/pull/209
