### ISSUE TITLE
[RFC]: Turbopack support

### ISSUE THREAD

**Issue by xalanq** [modern-js-dev/modern.js#1980]
### What problem does this feature solve?

有没有考虑支持 Turbopack 呀？
https://github.com/vercel/turbo

### What does the proposed API look like?

https://github.com/vercel/turbo

**Comment by chenjiahan** [comment]
近期我们也有调研 turbopack 哈，暂时没有办法接入 turbopack，因为现阶段 turbopack 只支持在 next.js 中使用，并不支持其他框架接入。

我们会继续保持观察，并调整我们的架构来支持「多构建引擎」，这部分架构调整将在 Modern.js 2.0 上线。等 turbopack 对外提供了接入方式，并达到一定成熟度的时候，我们会重新评估是否要接入。

另外字节跳动内部正在自研基于 rust 的 bundler —— rspack，并且会对 webpack 提供良好的兼容，等 rspack 达到一定完成度时，也会接入 modern.js 来提升编译效率。
