### ISSUE TITLE
[bug - 2.0]: confusing react version in peerDependencies

### ISSUE THREAD

**Issue by chenjiahan** [modern-js-dev/modern.js#2018]
### Version

```sh
next
```

### Details

The peerDependencies of @modern-js/runtime package is confusing:

![image](https://user-images.githubusercontent.com/7237365/199911822-3ee3537e-0930-416a-92b2-2082164b3230.png)

### Reproduce link

https://github.com/modern-js-dev/modern.js/blob/next/packages/runtime/plugin-runtime/package.json#L142

### Reproduce Steps

/

**Comment by caohuilin** [comment]
https://github.com/modern-js-dev/modern.js/pull/2042
