### ISSUE TITLE
好东西，但是。。。

### ISSUE THREAD

**Issue by fengsi** [modern-js-dev/modern.js#205]
咋和 Next.js 这么像 🤔

**Comment by guygubaby** [comment]
hello world 打包450kb, 惊了

**Comment by EchoZhaoH** [comment]
![image](https://user-images.githubusercontent.com/23427655/139615043-68c326ca-38f6-4043-960d-a42c306ea613.png)
![image](https://user-images.githubusercontent.com/23427655/139615049-0eb802e5-9b27-4f62-a4a3-e9359234c4ce.png)
打包出来的，觉没觉得有点大

**Comment by await-ovo** [comment]
> ![image](https://user-images.githubusercontent.com/23427655/139615043-68c326ca-38f6-4043-960d-a42c306ea613.png) ![image](https://user-images.githubusercontent.com/23427655/139615049-0eb802e5-9b27-4f62-a4a3-e9359234c4ce.png) 打包出来的，觉没觉得有点大
是比较大了， 我这边修复下
