### ISSUE TITLE
官网各种看不懂的名词，给爷👴看焦虑了都。

### ISSUE THREAD

**Issue by fujiazhang** [modern-js-dev/modern.js#210]

**Comment by wy2022** [comment]
确实，就不能写的简单明了点吗？

**Comment by yolio2003** [comment]
其实还好，各种名字反而让我理解清楚了之前别人都是吹啥，现在 modern 是实实在在解决了问题。

**Comment by BetterWorld-Liuser** [comment]
学不动辣学不动辣哈哈哈，这套东西设想是好的，我选择等等，等你到2.0。现在坑肯定很多。

**Comment by Albert-Gao** [comment]
从头到尾扫了一遍，我基本是React初就用的人，结论就是，想法还是蛮好的，不过还是老老实实nextjs吧，人家v12都已经alpha React 18的server components了。。。Serverside可以直接streaming部分渲染结果回客户端，相比之下，这个就有点上个年代了。。。当然也可以理解，人那个是社区豪华团体，FB+Google+Vercel。。。

**Comment by chkaos** [comment]
我看不懂但是我大受震撼！
