### ISSUE TITLE
Bug: git repository create failed

### ISSUE THREAD

**Issue by ahaoboy** [modern-js-dev/modern.js#215]
node: 16
ubuntu: 2110

![image](https://user-images.githubusercontent.com/19884146/139392292-a7de4c9a-6e5d-446b-bd8d-cc3509f17488.png)

**Comment by caohuilin** [comment]
@ahaoboy 可以尝试创建一个空目录，执行 `git init` 看看是否报错？

初步判断是 git 没有初始化造成的，可以执行下面的命令初始化之后，再尝试使用 @modern-js/create
$ git config --global user.name <userName>
$ git config --global user.email <email>

**Comment by ahaoboy** [comment]
> @ahaoboy 可以尝试创建一个空目录，执行 `git init` 看看是否报错？
> 
> 初步判断是 git 没有初始化造成的，可以执行下面的命令初始化之后，再尝试使用 @modern-js/create $ git config --global user.name $ git config --global user.email

thx
