### ISSUE TITLE
SSR 在服务刚启动的时候无效

### ISSUE THREAD

**Issue by snakeUni** [modern-js-dev/modern.js#221]
这是我使用 SSR 的[总结](https://github.com/snakeUni/note/blob/main/daily-study/2021-10-30.md)

个人测试是这样的原因：

`在项目启动的时候相当于服务重新启动，因为在执行到组件内部时，会把相应的函数注册到 loaderManger 中，因此第一次返回时 undefined，后续再刷新页面因为服务仍然在启动，仍然属于当前进程中，内部已经存在了当前的订阅器，因此可以等待之前注册的 loader 函数执行完再进行页面的渲染。`

**Comment by anc95** [comment]
我刚本地写了一个简单的 demo，没有复现「SSR 在服务刚启动的时候无效」的问题，不过我看了下你文档里描述的现象，应在服务端 SSR loader 执行出错了，降级到了客户端执行 loader。

> 但是后续再刷新的时候又发生了一个奇怪的现象是：服务端先返回 undefined，后续又返回了新的值，看起来是在服务端运行了多次。

SSR 的时候其实确实会渲染两次应用的，第一次渲染目的是收集到所有的 loader，然后等待 loader 执行完成后，再执行第二次渲染。这次完成之后，再把渲染的结果返回给客户端。

> 后续再刷新页面因为服务仍然在启动，仍然属于当前进程中，内部已经存在了当前的订阅器（loaderManager）。

这里的理解稍微有点不准确，`loaderManager` 对于每个请求都会在服务端创建一个对应实例，不同请求间肯定是隔离的，如上面所说的服务端 SSR 会走两次渲染，第一次（收集 loader）、第二次（使用已有的 loader数据渲染页面），在这个生命周期里使用的是一个 loaderManager。

**Comment by snakeUni** [comment]
明白了。

> SSR 的时候其实确实会渲染两次应用的，第一次渲染目的是收集到所有的 loader，然后等待 loader 执行完成后，再执行第二次渲染。

话说这样设计的目的是什么呢？为什么不是直接类似其他的 SSR 框架，在服务端把想要的数据执行完成后在客户端直接取其数据。渲染两次这样不是有额外的耗时么？如果是流式渲染的时候，这样是否会有问题？

**Comment by anc95** [comment]
你这里说的其它 SSR 如 nextjs 是通过 `getServerSideProps` 在服务端预取数据的。我们也考虑过这种方式，但出于一下原因没有使用：

1. Modern.js 既支持约定式路由，又支持自控式路由，对于约定式路由而言，给每个路由模块导出一个 `getServerSideProps` 静态函数获取服务端数据，是比较方便的。但对于自控路由而言，当前路由最终加载到了哪些组件是需要在服务端运行一遍才知道的，这种情况下使用相对中心化的 `getServerSideProps` 可能需要在根组件的 `getServerSideProps` 里面自己写一些路由匹配的逻辑，再写死当前路由需要取哪些数据，整体上负担会比较重。所以 Modern.js 里使用了相对去中心化的 `useLoader`，需要获取哪些数据完全取决了 React 路由匹配后直行到了哪些组件。
2. `getServerSideProps` 的另外一个问题是这个函数只在服务端运行，试想如果客户端重新执行这部分逻辑，那就需要在某种条件下，或者点击某个按钮后需要重新执行 `getServerSideProps` 中的部分逻辑，更新数据，那么就需要在组件里再复写这部分逻辑。（暂时没想道很好的例子举例说明）。而 `useLoader` 没这个问题，它内置了 `swr` 这样的 Query 管理方案的思想对客户端的 Loader 进行管理，可以手动重新执行 Loader 或者根据条件依赖 Loader 自动更新。
3. `useLoader` 的模式确实如你所说和 Suspense SSR 模式上看起来比较像，所以以后也方便旧项目向新的 SSR 架构迁移。

再说一下额外的损耗，确实是有的，我们在字节某个客户端上的活动页 SSR 的数据看，第一次渲染耗时基本在 10ms 以内，应该是可以接受的。如果对于 SSR 性能比较敏感也可以尝试结合 SPR（SSR 服务端缓存）。
