### ISSUE TITLE
请问 import { getPolyfillString } from '@modern-js/polyfill-lib' 是从哪里来的

### ISSUE THREAD

**Issue by anyexinglu** [modern-js-dev/modern.js#227]
源码里看到 import { getPolyfillString } from '@modern-js/polyfill-lib';
https://www.npmjs.com/package/@modern-js/polyfill-lib 里看到这个包的源头就是本仓库。
但是本仓库搜不到 getPolyfillString 方法的内容诶：https://github.com/modern-js-dev/modern.js/search?q=getPolyfillString&type=

**Comment by await-ovo** [comment]
这个 package 还没有放到 github 上维护，后续我们看下是否也提供出来

**Comment by anyexinglu** [comment]
> 这个 package 还没有放到 github 上维护，后续我们看下是否也提供出来

好的，谢谢大佬
