### ISSUE TITLE
Can't find the @modern-js/monorepo-tools packages in the Source Code

### ISSUE THREAD

**Issue by fireairforce** [modern-js-dev/modern.js#229]
May I  know where can i find the package `@modern-js/monorepo-tools` ? It seems don't include in the repo?

![image](https://user-images.githubusercontent.com/32598811/139554837-03e644c9-e775-4024-b9d4-7699842511f8.png)

**Comment by anc95** [comment]
Here is [@modern-js/monorepo](https://github.com/modern-js-dev/modern.js/tree/main/packages/solutions/monorepo-tools).

**Comment by fireairforce** [comment]
thx
