### ISSUE TITLE
建议文档页面的黑色header不要上滑就马上出现

### ISSUE THREAD

**Issue by joyexpr** [modern-js-dev/modern.js#231]
建议文档页面的黑色header不要上滑就马上出现，经常看文档里时想上滑一点看上面一点的文档，黑色header就马上出现，再下滑一点就消失，黑白冲突又强烈、且屏幕高度本来就比较小，header又占了一大块高度，看得眼睛很累、很烦躁

建议黑色header就只在上滑至页面最上方时才出现，在上滑时只要在右下角保留回到页首的按钮即可

**Comment by chenjiahan** [comment]
感谢反馈，顶部导航的交互已调整，近期会重新部署网站
