### ISSUE TITLE
新建的网站项目，启动报错

### ISSUE THREAD

**Issue by myfCode** [modern-js-dev/modern.js#236]
$ pnpm run dev

> website@0.1.0 dev D:\code\modernjs-learn\website
> modern dev

Starting the development server...
Failed to compile.

./src/App.tsx
Module parse failed: Unexpected token (9:2)
File was processed with these loaders:
 * ./node_modules/.pnpm/registry.npmmirror.com+@pmmmwh+react-refresh-webpack-plugin@0.4.3_38b60165483e1a76248535c34b16f9d1/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
You may need an additional loader to handle the result of these loaders.
|
| const App = () => (
>   <Switch>
|     <Route exact={true} path="/">
|       <div className="container">

Compiling...
Failed to compile.

**Comment by ShawDuChen** [comment]
the same problem
node version 14.17.6
pnpm version 6.20.1

> File was processed with these loaders:
 * ./node_modules/.pnpm/@pmmmwh+react-refresh-webpack-plugin@0.4.3_38b60165483e1a76248535c34b16f9d1/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js     
You may need an additional loader to handle the result of these loaders.
|
| const App = () => (
>   <div className="container">
|     <main>
|       <div className="logo">

**Comment by await-ovo** [comment]
和 #182 一样的问题

**Comment by AlanCZ** [comment]
和 #182 一样的问题
