### ISSUE TITLE
pnpm run new启用可选功能后，新依赖没有自动安装，需要手动再pnpm install

### ISSUE THREAD

**Issue by joyexpr** [modern-js-dev/modern.js#238]
按文档操作时：https://modernjs.dev/docs/start/mobile

pnpm run new启用可选功能后，新依赖项没有自动安装，需要手动再执行pnpm install
否则执行pnpm run dev会报错：error     Error: Can't call useContainer out of scope, it should be placed on top of the function

操作系统：macos 10.15.7
node版本：nvm 14.18.1
pnpm版本：6.19.1

**Comment by caohuilin** [comment]
> 按文档操作时：https://modernjs.dev/docs/start/mobile
> 
> pnpm run new启用可选功能后，新依赖项没有自动安装，需要手动再执行pnpm install 否则执行pnpm run dev会报错：error Error: Can't call useContainer out of scope, it should be placed on top of the function
> 
> 操作系统：macos 10.15.7 node版本：nvm 14.18.1 pnpm版本：6.19.1

@joyexpr 请问是执行 pnpm run new 开启哪个可选功能出现的依赖没有自动安装？

**Comment by joyexpr** [comment]
> @joyexpr 请问是执行 pnpm run new 开启哪个可选功能出现的依赖没有自动安装？

试了几个，都没有自动安装依赖，如unbundle、bff等

**Comment by caohuilin** [comment]
> > @joyexpr 请问是执行 pnpm run new 开启哪个可选功能出现的依赖没有自动安装？
> 
> 试了几个，都没有自动安装依赖，如unbundle、bff等

unbundle 是已知问题，没有执行 install 之后的 scripts 钩子导致的，已经修复，可以删除项目 node_modules 和 pnpm-lock.yaml 重新安装依赖后重试。 

bff 启用不装依赖的问题可以给我截个图吗？

**Comment by caohuilin** [comment]
https://github.com/modern-js-dev/codesmith/pull/12
