### ISSUE TITLE
[Bug]: 关闭 config/public 内 html 文件的编译检查

### ISSUE THREAD

**Issue by xalanq** [modern-js-dev/modern.js#2381]
### 版本信息

```sh
├── @modern-js/app-tools@1.21.6 -> ./node_modules/.pnpm/@modern-js+app-tools@1.21.6_kj4jjlrxxnopboqrxiwddbesd4/node_modules/@modern-js/app-tools
└─┬ @modern-js/plugin-electron@2.0.14 -> ./node_modules/.pnpm/@modern-js+plugin-electron@2.0.14_h7ljqjzjdwt2fdmeqkgp4yfjd4/node_modules/@modern-js/plugin-electron
  └── @modern-js/app-tools@1.21.6 -> ./node_modules/.pnpm/@modern-js+app-tools@1.21.6_kj4jjlrxxnopboqrxiwddbesd4/node_modules/@modern-js/app-tools
```

### 问题详情

modernjs 好像会对 config/public 内的 html 进行编译检查，而不是直接 copy 并作为静态资源使用
请问如何关闭这个功能？html 文件可能存在问题，但也想让编译成功进行

### 复现链接

无

### 复现步骤

```
$ npx @modern-js/create hello-modern
? Please select the solution you want to create MWA Solution
? Development Language TS
? Package Management Tool pnpm
? Do you need to support the following types of applications Not Enabled
? Modify the Default Configuration? No
```

之后将这个 html 文件复制到 `config/public` 文件夹内 [mitm.html.zip](https://github.com/modern-js-dev/modern.js/files/10223906/mitm.html.zip)

文件来源：https://github.com/jimmywarting/StreamSaver.js/blob/master/mitm.html

```
$ cd hello-modern
$ ls config/public
mitm.html
```

之后编译会报错

```
$ pnpm dev

> hello-modern@0.1.0 dev hello-modern
> modern dev

✖ Client
  Compiled with some errors in 1.27s

Starting the development server...
Failed to compile.

scope is not defined
```

![image](https://user-images.githubusercontent.com/30496124/207494735-31ffbcd2-6860-49f8-80af-2022969c8944.png)

**Comment by chenjiahan** [comment]
目前在 copy HTML 文件时会通过 lodashTemplate 来注入 assetPrefix 变量，应该是 lodashTemplate 解析时抛出的异常，我们看一下怎么处理

![image](https://user-images.githubusercontent.com/7237365/207495540-b9260fb4-4e68-4ac4-bd3e-055c7436f2d2.png)

**Comment by xalanq** [comment]
麻烦发一个 v1 的版本哈 [比心]

**Comment by caohuilin** [comment]
明天发哈

**Comment by xalanq** [comment]
@chenjiahan 有一个新的 bug

步骤同上，现在是可以编译了，但是访问 html 会 404（别的资源正常访问）

dist 文件夹里的 route.json 长这样：

```
{
  "routes": [
    {
      "urlPath": "/",
      "entryName": "main",
      "entryPath": "html/main/index.html",
      "isSPA": true,
      "isSSR": false,
      "enableModernMode": false
    },
    {
      "urlPath": "/mitm.html",
      "isSPA": true,
      "isSSR": false,
      "entryPath": "public/mitm.html"
    }
  ]
}
```

看起来是有路由的，但是 curl 的时候是 404（我本地起的测试 demo 端口是 8081）

![image](https://user-images.githubusercontent.com/30496124/207803738-bb4a9364-1bd3-4c55-abc4-31ce5ca5f94a.png)

**Comment by chenjiahan** [comment]
麻烦给个复现步骤哈

**Comment by xalanq** [comment]
> 麻烦给个复现步骤哈，最好有复现仓库

步骤就是问题描述的那个步骤，一个空的 hello-modern 项目，在 config/public 里加入一个 mitm.html，然后 pnpm dev 运行
访问 http://[host]:[port]/mitm.html 就能复现

**Comment by xalanq** [comment]
请问有跟进吗🥺🥺

**Comment by xalanq** [comment]
@chenjiahan 🥺🥺

**Comment by chenjiahan** [comment]
@xalanq 按照你描述的步骤尝试了下，没复现出来哈。要不提供下复现仓库

<img width="1257" alt="截屏2023-01-09 下午10 03 34" src="https://user-images.githubusercontent.com/7237365/211326101-6b60d1e9-fb60-42f7-8a7f-c7f3aef9123b.png">

**Comment by xalanq** [comment]
https://github.com/xalanq/hello-modern-issue-2381
步骤没变 @chenjiahan 
辛苦！

```
$ npm ls @modern-js/app-tools
hello-modern@0.1.0 ~/hello-modern
└── @modern-js/app-tools@1.22.3 -> ./node_modules/.pnpm/@modern-js+app-tools@1.22.3_typescript@4.9.4/node_modules/@modern-js/app-tools
```

**Comment by chenjiahan** [comment]
@xalanq 看了下确实有问题，跟 Modern.js 版本有关，我们再深入排查下

**Comment by xalanq** [comment]
@chenjiahan @caohuilin 看到修复了，年前能发个版不🥺❤️❤️

**Comment by caohuilin** [comment]
可以的，明天发一个

**Comment by caohuilin** [comment]
@xalanq https://github.com/modern-js-dev/modern.js/releases/tag/v1.22.5 发好了
