### ISSUE TITLE
npx @modern-js/create mobile-pages 报错

### ISSUE THREAD

**Issue by Nicolerobinn** [modern-js-dev/modern.js#242]
![image](https://user-images.githubusercontent.com/48322373/139640061-df3d28dd-9a23-4c90-b6c6-bd42c7d75589.png)

**Comment by caohuilin** [comment]
@Nicolerobinn 这个是获取生成器相关的 npm 包超时了，检查一下网络重试一下看看

**Comment by theseusyang** [comment]
遇到过相同问题

**Comment by caohuilin** [comment]
> 遇到过相同问题

重试不行的话可以考虑换taobao镜像试试
