### ISSUE TITLE
project init fail

### ISSUE THREAD

**Issue by lie5860** [modern-js-dev/modern.js#256]
npx @modern-js/create api-lie

sh: create: 未找到命令

------------------------------
env:

node -v
v16.13.0

pnpm -v
6.20.1

cat /proc/version
Linux version 3.10.0-1160.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Mon Oct 19 16:18:59 UTC 2020

**Comment by lie5860** [comment]
直接使用create api-lie 可以运行。
但是运行pnpm run new 又报错

pnpm run new

> api-lie@0.1.0 new /d4t/studyItems/api-lie
> modern new

sh: modern: 未找到命令

**Comment by lie5860** [comment]
先npm i 一下项目 就可以执行pnpm run new了。感觉哪里怪怪的。我之前用centos8的环境 运行就好好地。
也没有显示说依赖git 初始化项目的时候提示我git不存在。。

**Comment by lie5860** [comment]
运行报错 报错信息太长了 看不到前面的
![image](https://user-images.githubusercontent.com/30894657/140003572-cd3a25ce-292c-47df-856f-84b744475b05.png)

**Comment by await-ovo** [comment]
辛苦提供下可复现的步骤或者demo

**Comment by lie5860** [comment]
> 辛苦提供下可复现的步骤或者demo

我每一步都有贴命令诶。
首先根据文档安装了nvm 然后nvm安装了node v16 pnpm
然后执行 npx @modern-js/create api-lie 报错sh: create: 未找到命令。我直接执行了create api-lie 可以运行。然后项目直接运行pnpm run new 报错。在工程目录npm i 一下就可以运行pnpm run new。然后运行pnpm run dev 就报最后截图的错了。

如果有必要我可以提供ssh环境供复现，wechat : lie474993382

**Comment by caohuilin** [comment]
> > 辛苦提供下可复现的步骤或者demo
> 
> 我每一步都有贴命令诶。 首先根据文档安装了nvm 然后nvm安装了node v16 pnpm 然后执行 npx @modern-js/create api-lie 报错sh: create: 未找到命令。我直接执行了create api-lie 可以运行。然后项目直接运行pnpm run new 报错。在工程目录npm i 一下就可以运行pnpm run new。然后运行pnpm run dev 就报最后截图的错了。
> 
> 如果有必要我可以提供ssh环境供复现，wechat : lie474993382

@lie5860 微信联系

**Comment by caohuilin** [comment]
环境问题，已解决
