### ISSUE TITLE
[RFC]: `source.globalVars` 区分值为 undefined 时的行为

### ISSUE THREAD

**Issue by Asuka109** [modern-js-dev/modern.js#2692]
### What problem does this feature solve?

目前的版本直接使用 `globalVars` 定义环境变量时，如果变量为空会导致定义被忽略，于是相关逻辑代码会发生 `process is not defined` 之类的问题。

### What does the proposed API look like?

修改 `globalVars` 的注入逻辑，细节待补完

**Comment by chenjiahan** [comment]
那设置 undefined 应该注入啥
