### ISSUE TITLE
自定义postcss 插件bug

### ISSUE THREAD

**Issue by liruiqing** [modern-js-dev/modern.js#283]
文档地址：https://modernjs.dev/docs/guides/usages/css/postcs
![image](https://user-images.githubusercontent.com/9715654/140679244-a51dcfe6-72ca-4977-9d2f-eb67663cc853.png)
按照文档中的配置，本地会报错
![image](https://user-images.githubusercontent.com/9715654/140679369-dc24c407-bdb2-4136-818d-ac4156e41d6f.png)

**Comment by await-ovo** [comment]
```js
tools: {
  postcss: {
    postcssOptions: {}
  }
}
```
文档上有点问题，需要修复下，可以按上面的方式配置。
也可以这样: https://modernjs.dev/docs/apis/config/tools/postcss 配置函数直接改。

**Comment by liruiqing** [comment]
配置了modern.config.js，添加 postcss-pxrorem 插件报错，代码如下

import { defineConfig } from '@modern-js/app-tools';
import postcssPxtorem from 'postcss-pxtorem';

export default defineConfig({
  runtime: {
    router: true,
    state: true,
  },
  tools: {
    postcss: {
      postcssOptions: {
        plugins: [
          postcssPxtorem({
            rootValue: 16,
            unitPrecision: 5,
            propList: ['font', 'font-size', 'line-height', 'letter-spacing'],
            selectorBlackList: [],
            replace: true,
            mediaQuery: false,
            minPixelValue: 0,
            exclude: /node_modules/i,
          }),
        ],
      },
    },
  },
});

![image](https://user-images.githubusercontent.com/9715654/141219987-2d859950-fd50-4bdd-b59d-5fc2145085f1.png)

**Comment by chenjiahan** [comment]
tools.postcss 文档已更新，可以参考下：https://modernjs.dev/docs/apis/config/tools/postcss

另外我试了 postcss-pxtorem 插件是可以正常使用的，建议检查下 postcss-pxtorem 安装的版本是否正确，或者后续提供一个复现的最小仓库，我们排查下。
