### ISSUE TITLE
configuration of tools.webpack is not available

### ISSUE THREAD

**Issue by EYHN** [modern-js-dev/modern.js#294]
Following the example in the [document](https://modernjs.dev/docs/apis/config/tools/webpack), I created `modern.config.js` with following code. But it didn't work.

``` js
const { defineConfig } = require('@modern-js/app-tools');

module.exports = defineConfig({
  tools: {
    webpack: { mode: 'development' },
  },
});
```

By reading the [source code here](https://github.com/modern-js-dev/modern.js/blob/main/packages/cli/webpack/src/config/base.ts#L660), I found that the only way to make it available is to use `webpack-chain`.

```js
const { defineConfig } = require('@modern-js/app-tools');

module.exports = defineConfig({
  tools: {
    webpack: (config, { chain }) => {
      chain.mode('development');
    },
  },
});
```

This may be a bug or the documentation may need to be fixed.

**Comment by chenjiahan** [comment]
Currently only webpack-chain is available, the document has been updated.

https://modernjs.dev/docs/apis/config/tools/webpack
