### ISSUE TITLE
[RFC]: v2 对 electron 的支持

### ISSUE THREAD

**Issue by xalanq** [modern-js-dev/modern.js#3007]
### What problem does this feature solve?

请问有没有像 v1 那样支持 electron 的计划？

### What does the proposed API look like?

无

**Comment by chenjiahan** [comment]
由于 Modern.js 整体规划调整，从 Modern.js 2.0 版本开始，将不再提供 Electron 工程方案。

如果有相关需求，欢迎 fork Modern.js v1 的 Electron 相关代码进行二次开发，感谢理解~
