### ISSUE TITLE
[Monorepo & library packages]: `modern new` not executable in monorepo packages

### ISSUE THREAD

**Issue by lianghx-319** [modern-js-dev/modern.js#314]
## Reproduce
- [repository for test](https://github.com/bytesfriends/twin.arco)
- Steps
  - `git clone`
  - `pnpm i`
  - `pnpm run new --filter twin.arco`
![image](https://user-images.githubusercontent.com/27187946/142094934-884f5cf1-6472-4090-9f2b-c2062530b203.png)

## Expected
- I want to check unbundle mode available in module solution or not.
- Maybe use `esbuild` or `swc` as build tools for `node library` is a better option.

**Comment by caohuilin** [comment]
That is bug for new action.
You can add `"peerDependencies": {}` to package.json to hack resolve this error.
This week release will resolve this problem.

Module solution not support unbundle currently！
