### ISSUE TITLE
dev:esm运行的时候，引用scss会报错，这个是因为什么

### ISSUE THREAD

**Issue by KStephening** [modern-js-dev/modern.js#323]
![image](https://user-images.githubusercontent.com/23191186/142520119-88550ea0-f3d5-417f-9956-d3d793de3fbd.png)

**Comment by chenjiahan** [comment]
@KStephening 未能复现此问题，这个 issue 时间有点久了，先 close 咯。

如果你依然能复现这个问题，请提供一个复现问题的仓库链接，我们会重新打开此 issue。
