### ISSUE TITLE
nest 在框架写法下无法运行

### ISSUE THREAD

**Issue by nervouself** [modern-js-dev/modern.js#333]
node version：14.18.1
pnpm version：6.22.1

稳定复现：是

### 复现路径：

1. npx @modern-js/create
log:
npx: 1 安装成功，用时 1.746 秒
? 请选择你想创建的工程类型 应用
? 请选择开发语言 TS
? 请选择包管理工具 pnpm
? 是否需要支持以下类型应用 不需要
? 是否需要调整默认配置? 否

2. pnpm run new
log:
? 请选择你想要的操作 启用可选功能
? 启用可选功能 启用「BFF」功能
? 请选择 BFF 类型 框架模式
? 请选择运行时框架 Nest

3. pnpm run dev
log:
● Client █████████████████████████ setup (3%)  
 watch run

[Nest] 96690  - 2021/11/23 下午3:47:41     LOG [NestFactory] Starting Nest application...
[Nest] 96690  - 2021/11/23 下午3:47:41   ERROR [ExceptionHandler] Nest can't resolve dependencies of the AppController (?). Please make sure that the argument Object at index [0] is available in the AppModule context.

Potential solutions:
- If Object is a provider, is it part of the current AppModule?
- If Object is exported from a separate @Module, is that module imported within AppModule?
  @Module({
    imports: [ /* the Module containing Object */ ]
  })

### 最小复现代码
[nest-test.zip](https://github.com/modern-js-dev/modern.js/files/7586473/nest-test.zip)

**Comment by tqma113** [comment]
正在测试

**Comment by nervouself** [comment]
我的飞书账号是：https://www.feishu.cn/invitation/page/add_contact/?token=4edsdc34-ace6-4e55-ad4d-9fae56b6b717
方便的话可以直接沟通

**Comment by chenjiahan** [comment]
测试了下，这个问题已经修复了，目前按照上述步骤可以正常运行。
