### ISSUE TITLE
当打开BFF和SSR模式的时候，浏览器两个tag打开页面，页面会反复刷新

### ISSUE THREAD

**Issue by Laoll** [modern-js-dev/modern.js#338]
当打开BFF和SSR模式的时候，浏览器两个tag打开页面，页面会反复刷新
![image](https://user-images.githubusercontent.com/23629215/143227075-f0140ef1-1eb7-44d8-a18c-776296ea831c.png)
![image](https://user-images.githubusercontent.com/23629215/143227223-6f78a733-fd7b-46cb-9261-610d310ac928.png)

**Comment by yimingjfe** [comment]
开启 ssr，使用两个 tab  打开页面可以复现该问题。

**Comment by zllkjc** [comment]
应该是热更新的 websocket message 导致，我看一下

**Comment by l2xBrain** [comment]
遇到同样的问题
