### ISSUE TITLE
启用「Visual Testing (Storybook)」模式报错

### ISSUE THREAD

**Issue by extheor** [modern-js-dev/modern.js#352]
| Loading...[ERROR] run task error: Error: Cannot find module 'C:\Users\xxx\AppData\Local\Temp\csmith-generator\@modern-js\dependence-generator@1.1.0\dist\js\node\main.js'. Please verify that the package.json has a valid "main" entry

**Comment by extheor** [comment]
删了 C:\Users\xxx\AppData\Local\Temp\csmith-generator@modern-js 目录下的 @modern-js 问题已经解决

**Comment by caohuilin** [comment]
@modern-js/create 和 new 命令默认会在系统 <tmp>/csmith-generator 目录下进行缓存生成器包，这种情况看起来是缓存文件过程中从 npm 拉的包出现了错误，删除缓存文件重新拉最新的包即可。
