### ISSUE TITLE
`modern inspect` has not been implemented

### ISSUE THREAD

**Issue by faxinwang** [modern-js-dev/modern.js#376]
https://modernjs.dev/docs/apis/config/tools/webpack 这个文档里面说的 `modern inspect` 命令好像并没有实现；
`dist/webpack.inspect.js` 这个文件是在哪里呢，没有说清楚呢。

**Comment by xuchaobei** [comment]
`inspect` 命令的最终设计还没有确定，文档中的这部分内容稍后会做修改，感谢反馈！

**Comment by chenjiahan** [comment]
文档已更新：https://modernjs.dev/docs/apis/config/tools/webpack
