### ISSUE TITLE
production 安装下 server 无法启动

### ISSUE THREAD

**Issue by nervouself** [modern-js-dev/modern.js#383]
原因是 modern 命令由 `@modern-js/app-tools` 库提供，在 production 安装下这个库不会安装，执行 `modern start` 会报 modern 命令找不到；将 `@modern-js/app-tools` 加入到 dependencies，启动时又要求安装 `@modern-js/tsconfig`、`@modern-js/plugin-jarvis` 等其他插件，这些插件又是运行时不需要的

请问下有优化方案吗？

**Comment by zllkjc** [comment]
这里部署方式是怎么样的，能将构建完的整个仓库用于部署吗。目前的确没有单独提供运行时的产物。

**Comment by nervouself** [comment]
完整部署的话对于大的 monorepo 不太友好，镜像太大的话构建和占用磁盘空间都比较大
