### ISSUE TITLE
使用内置的Web 服务器部署，如何直接进程守护方式启动

### ISSUE THREAD

**Issue by l2xBrain** [modern-js-dev/modern.js#390]
pnpm run start 之后，因为采用了SSR，有没有类似pm2的方式启动，
1. 直接后台启动，
2. 自动重启

**Comment by zllkjc** [comment]
新建一个 sh 文件，执行 pnpm run start，然后 pm2 启动这个 sh 文件就可以吧

**Comment by l2xBrain** [comment]
@zllkjc pm2 可以启动 shell 文件吗？

**Comment by zllkjc** [comment]
https://pm2.keymetrics.io/docs/usage/quick-start/

**Comment by zllkjc** [comment]
看起来是可以执行 sh 文件的

**Comment by l2xBrain** [comment]
nice work
