### ISSUE TITLE
After modifying the state in react DOM, the store state obtained by the custom function is still null

### ISSUE THREAD

**Issue by bluelong001** [modern-js-dev/modern.js#395]
**### Steps to reproduce**

// models/user.ts
//
// state: { token:""}
// actions: { login: (state)=>{ state.token="xxxx" }

1,
in Login.tsx

const [{token}, actions] = useModel(use)
actions.login()  // actions: { login: (state)=>{ state.token="xxxx" }

**after login ok**
useEffect(()=>{
console.log(token) //"xxxx"
},[token])

2,
in services.ts

const store=createStore()

const getToken()=>{

const [{token},actions]= store.use(user);
console.log(token) //""
}

**### What is expected?**
in services.ts
state.token="xxxx"

**### What is actually happening?**
state.token=""

**Comment by bluelong001** [comment]
in services.ts

const store=createStore()

const getToken()=>{

const [{token},actions]= store.use(user);
actions.login() //Exception: login is not a function
}

**Comment by ycaptain** [comment]
同步信息：在 Modern.js 官方飞书群中讨论确认了问题。在约定式路由应用中， _app.tsx 中使用 Provider 指定自定义 store 后，在子页面中 useModel 时，会报错，待修复。
