### ISSUE TITLE
按入口设置HTML模板不生效

### ISSUE THREAD

**Issue by coder-log666** [modern-js-dev/modern.js#400]
![image](https://user-images.githubusercontent.com/77562437/146633102-5a6e9860-c8b8-41de-905d-c563ae56bfd2.png)
开发网站项目，按入口设置HTML模板不生效，是配置有问题吗？

**Comment by xuchaobei** [comment]
你这里入口理解有误，你的项目只有一个入口（整个pages/ 是一个入口），article/ 对应的只是一个路由，不是入口。 一个入口对应的是最终生成的一个独立的 html 文件。
