### ISSUE TITLE
官网文档勘误

### ISSUE THREAD

**Issue by mohuai99** [modern-js-dev/modern.js#406]
官网文档 =》 扩展插件 Hook 章节，下面的创建 Demo 的命令是不是有误？

原命令：
$ npx @modern-js/core modern-js-demo

是否应该修正为：
$ npx @modern-js/create modern-js-demo

**Comment by mohuai99** [comment]
同一章节还有一处

这时运行 npx modern message 就会执行相关逻辑，但由于没有手机到任何信息，所以控制台输出为空。

此处的 【手机】是否应为 【收集】

**Comment by rqzheng2015** [comment]
已收到建议，将在近期修复

**Comment by rqzheng2015** [comment]
已修复，可查看[文档](https://modernjs.dev/docs/guides/features/custom/framework-plugin/extend)验证修复结果
