### ISSUE TITLE
Environment variable not working

### ISSUE THREAD

**Issue by jiahao-c** [modern-js-dev/modern.js#411]
## Issue
Environment variables configured in `.env.development`  is not read 

## Code
`/.env.development`:
```
URL="https://example.com"
YEAR=2021
```

`/src/pages/index.tsx`:
```JSX
    <p>process.env.NODE_ENV : {process.env.NODE_ENV}</p>
    <p>process.env.URL : {process.env.URL}</p>
    <p>process.env.YEAR : {process.env.YEAR} </p>
```

### Result
```
process.env.NODE_ENV : development
process.env.URL :
process.env.YEAR : 
```

### Expected
```
process.env.NODE_ENV : development
process.env.URL : https://example.com
process.env.YEAR : 2021
```

### Console
No console error or warning

### name and directory
根据 [文档](https://modernjs.dev/docs/apis/runtime/env)，将 `.env.development` 文件放在了项目根目录。
另外还尝试了
1. 放在`/src`目录
2. 文件名用 `.env` 
但都没有作用。

### runtime version
```
dependencies:
  '@modern-js/runtime': 1.1.1
```

## Reproduce Steps
1. 使用 `npx @modern-js/create hello-modern` 新建项目
2. 使用 `.env.development` 设置环境变量
3. 在JSX中使用设置的环境变量

**Comment by xuchaobei** [comment]
请升级到 1.1.4 版本，这个版本修复了问题

**Comment by jiahao-c** [comment]
> 请升级到 1.1.4 版本，这个版本修复了问题

谢谢回复。请问指的是 `@modern-js/app-tools` 还是 `@modern-js/runtime`呢？前者已经在使用最新版1.1.5了，后者目前[npm最新版本](https://www.npmjs.com/package/@modern-js/runtime-core)只有1.1.1。

**Comment by xuchaobei** [comment]
在package.json 中的 "modernConfig" 增加如下配置，才能在前端代码中使用 `YEAR`  环境变量：
```
"source": {
      "envVars": [
        "YEAR"
      ]
 }
```

自定义的环境变量，需要手动在 `envVars` 中指定，才能被使用。
这块文档上缺少解释，后续会补充，抱歉。

**Comment by jiahao-c** [comment]
感谢解答！
P.S. 我看到了文档的 [gh-pages repo](https://github.com/modern-js-dev/modern-js-dev.github.io)，不过似乎只有编译后的静态页面。如果能够开源编译前文档的话，很乐意协助编辑和翻译～

**Comment by xuchaobei** [comment]
> 感谢解答！ P.S. 我看到了文档的 [gh-pages repo](https://github.com/modern-js-dev/modern-js-dev.github.io)，不过似乎只有编译后的静态页面。如果能够开源编译前文档的话，很乐意协助编辑和翻译～

文档会尽快在 github 上放出，欢迎共建！
