### ISSUE TITLE
建议: 在README中明示一下这个仓库发布的npm包名称。

### ISSUE THREAD

**Issue by faxinwang** [modern-js-dev/modern.js#412]
建议说明一下该仓库发的npm包的名称，@modern-js下面有那么多包，不说清楚这是那个包，都不知道要更新哪个包了。

**Comment by xuchaobei** [comment]
每个 package.json 中的 name 字段对应的就是这个包在 npm 中的包名称。
另外，一般情况下，用户也不需要关注包名，当需要开启某项功能时，只要根据文档执行 new 命令，进行相应选择，会自动安装该功能所需的插件依赖。

**Comment by faxinwang** [comment]
有些包它本身不是作为插件出现的，也不需要用户自己升级吗，比如@modern-js/core这个包。

**Comment by xuchaobei** [comment]
@modern-js/core 是底层依赖包，用户不直接触，一般也不需要关注版本。用户升级上层包时，Modern.js 会保证依赖的底层包版本的正确性。

**Comment by faxinwang** [comment]
嗯嗯，其实主要问题是我不知道哪些包是需要自己手动升级的上层包，官网的文档里面好像也没有看到相关的说明。

**Comment by chenjiahan** [comment]
关于升级这个问题，目前可以通过以下命令升级：

```bash
pnpm update "@modern-js/*" -r
```

后续我们会计划提供 upgrade 命令，相关 issue：https://github.com/modern-js-dev/modern.js/issues/850
