### ISSUE TITLE
hot reload 必现 Uncaught ReferenceError 并锁死页面

### ISSUE THREAD

**Issue by jiahao-c** [modern-js-dev/modern.js#413]
## reproduce steps
1. `npx @modern-js/create website` 创建项目 （或直接 clone [这个 repo](https://github.com/jiahao-c/modernjs-bug-reproduce-2)）
2. `pnpm run dev` 开发模式启动项目
3.  编辑 JSX 内容并保存，触发 hot reload
例如，把 `index.tsx` 中的 `ok` 编辑为 `hi`
4. console 报错 `Uncaught ReferenceError: process is not defined`，同时页面会失去响应（ input 和 button 等元素都无法点击，除非手动再次刷新页面直至 console 不再报错）
![image](https://user-images.githubusercontent.com/8275280/147422712-76c4bf00-97f3-4955-a580-de2567051c89.png)

## Suspected cause
可能是 `@modern-js/hmr-client` 的问题？因为 error stack 里有它。

## Version
见 [pnpm-lock.yaml](https://github.com/jiahao-c/modernjs-bug-reproduce-2/blob/main/pnpm-lock.yaml)

**Comment by chenjiahan** [comment]
此 issue 可以关闭了，已在此 PR 中被修复：https://github.com/modern-js-dev/modern.js/pull/517

@ycaptain
