### ISSUE TITLE
stackblitz 上面使用 npx @modern-js/create 初始化项目失败

### ISSUE THREAD

**Issue by leeight** [modern-js-dev/modern.js#418]
```
~/projects/node-yxlujt 28s
❯ npx @modern-js/create
success Install finished in 0.792s

⠋ Loading...[ERROR] load remote generator failed: Package @modern-js/repo-generator could not be found or get timeout
[ERROR] run task error: Error: load generator failed
    at GeneratorCore.runGenerator (/home/.turbo/npx/OfULla/node_modules/@modern-js/create/dist/js/node/main.js:304:13)
    at async CodeSmith.runTask (/home/.turbo/npx/OfULla/node_modules/@modern-js/create/dist/js/node/main.js:75:5)
    at async CodeSmith.forge (/home/.turbo/npx/OfULla/node_modules/@modern-js/create/dist/js/node/main.js:58:9)
    at async Command.createAction (/home/.turbo/npx/OfULla/node_modules/@modern-js/create/dist/js/node/main.js:218142:5)
```

![image](https://user-images.githubusercontent.com/104052/147461799-ebc865c0-b277-4caf-967b-4a16d24a5da9.png)

**Comment by caohuilin** [comment]
> ```
> ~/projects/node-yxlujt 28s
> ❯ npx @modern-js/create
> success Install finished in 0.792s
> 
> ⠋ Loading...[ERROR] load remote generator failed: Package @modern-js/repo-generator could not be found or get timeout
> [ERROR] run task error: Error: load generator failed
>     at GeneratorCore.runGenerator (/home/.turbo/npx/OfULla/node_modules/@modern-js/create/dist/js/node/main.js:304:13)
>     at async CodeSmith.runTask (/home/.turbo/npx/OfULla/node_modules/@modern-js/create/dist/js/node/main.js:75:5)
>     at async CodeSmith.forge (/home/.turbo/npx/OfULla/node_modules/@modern-js/create/dist/js/node/main.js:58:9)
>     at async Command.createAction (/home/.turbo/npx/OfULla/node_modules/@modern-js/create/dist/js/node/main.js:218142:5)
> ```
> 
> ![image](https://user-images.githubusercontent.com/104052/147461799-ebc865c0-b277-4caf-967b-4a16d24a5da9.png)

查了一下是因为 stackblitz 上的 yarn 是它内部基于 https://www.npmjs.com/package/turbo-cli 重新封装的，install 命令不支持 --production 参数造成的

**Comment by leeight** [comment]
所以后续会修复吗？

**Comment by caohuilin** [comment]
> 所以后续会修复吗？

这个根本原因是 stackblitz 不兼容 yarn 的命令参数造成的，后续可以做兼容，优先级不算高
