### ISSUE TITLE
npm run dev failed in @modern-js/core

### ISSUE THREAD

**Issue by hardfist** [modern-js-dev/modern.js#420]
I try to build @modern-js/core in watch mode  but failed. and build mode without watch succeed at commit(90eeb72c88b21f4c943fb4a7c585e7191be78796)
![image](https://user-images.githubusercontent.com/8898718/147488871-1ca043fd-7b09-44ba-98f0-ed23d8559023.png)

**Comment by chenjiahan** [comment]
这个问题不再复现了，close 咯
