### ISSUE TITLE
问一下，多页面模式，这个并不是 tsx/jsx 为什么也会生成路由呢，应该怎么禁止这种行为

### ISSUE THREAD

**Issue by GuoYiJi** [modern-js-dev/modern.js#426]
![image](https://user-images.githubusercontent.com/13943322/147630857-0e554b05-a92f-467b-a225-78a12c8c63fa.png)

**Comment by await-ovo** [comment]
可以把 store 放到 common 目录下，比如还有其他的 utils 都可以放到 common 目录。只要 common 目录下面没 index 是不会当成页面入口的。目录结构类似这样:
  
 ```
- src
  - common 
     - utils
     - store
        index.js 
  - a1
     index.js 
  - a2
    index.js
```

**Comment by GuoYiJi** [comment]
好的，明白了，是可以解决，但我理解是不是页面入口的逻辑收集，加上明显的特征标识会好一点，比如必须是 jsx/tsx，不然一个 index 其实可能不是入口

**Comment by await-ovo** [comment]
> 好的，明白了，是可以解决，但我理解是不是页面入口的逻辑收集，加上明显的特征标识会好一点，比如必须是 jsx/tsx，不然一个 index 其实可能不是入口

通过后缀确实不太好区分，比如 js 也可以是具体的页面。应该可以在文件内容里面加些东西，来避免当做入口~
