### ISSUE TITLE
Date.now() 使用问题

### ISSUE THREAD

**Issue by snakeUni** [modern-js-dev/modern.js#429]
如果在组件中使用 Date.now()，那么在服务端返回再到客户端渲染的时候会有一个时间差，这个会造成 did not match 的警告，想问下如何解决这种即时性非常高的时间问题呀。

**Comment by await-ovo** [comment]
这个其实文档的例子里就有说明, 可以使用 [`NoSSR` ](https://modernjs.dev/docs/apis/runtime/app/no-ssr)组件优化

**Comment by snakeUni** [comment]
好的呀。针对这种目前是只能使用 `NoSSR` 组件包裹了。感谢
