### ISSUE TITLE
把modern.config.js 改成 modern.config.ts发生了类型错误

### ISSUE THREAD

**Issue by hatch1994** [modern-js-dev/modern.js#433]
```
import { defineConfig } from '@modern-js/app-tools';

export default defineConfig({
  runtime: {
    masterApp: {
      manifest: {
        modules: [
          {
            name: 'Dashboard',
            entry: 'http://localhost:8081',
          },
          {
            name: 'TableList',
            entry: 'http://localhost:8082',
          },
        ],
      },
    },
  },
})
```

**Comment by hatch1994** [comment]
File '/Users/***/Workspaces/frontend/***/node_modules/.pnpm/@modern-js+app-tools@1.1.5_bad060d5f9aca5284661d88d739ba15b/node_modules/@modern-js/app-tools/lib/types.d.ts' is not a module.ts(2306)

**Comment by hatch1994** [comment]
我需要官方的帮助!

**Comment by ycaptain** [comment]
@modern-js/app-tools 类型导出存在 bug，正在修复中

**Comment by ycaptain** [comment]
可以先使用 `modern.config.js`

**Comment by jiahao-c** [comment]
我尝试使用 `modern.config.js`，但无法正常引入 defineConfig。以下两种方法， `pnpm run dev` 会都报错：

```typescript
import { defineConfig } from '@modern-js/app-tools';
```

```typescript
const { defineConfig } = require('@modern-js/app-tools');
```

```bash
> modern dev
error     Error: Couldn't find property defineConfig of /defineConfig
    at /.../node_modules/.pnpm/better-ajv-errors@0.7.0_ajv@8.8.2/node_modules/better-ajv-errors/lib/modern/json/get-meta-from-path.js:18:19
```

**Comment by ycaptain** [comment]
@jiahao-c 可以直接导出，如：
```js
module.exports = {
    runtime: {
        state: true
    }
}
```

**Comment by jiahao-c** [comment]
> @jiahao-c `defineConfig` 是为了提供类型提示而提供的函数，直接导出对象效果也是一样的。 在修复 `@modern-js/app-tools` 可以直接导出对象，如：
> 
> ```js
> module.exports = {
>     runtime: {
>         state: true
>     }
> }
> ```

感谢秒速回复！！节假日工作辛苦了！

**Comment by ycaptain** [comment]
> @jiahao-c `defineConfig` 是为了提供类型提示而提供的函数，直接导出对象效果也是一样的。 在修复 `@modern-js/app-tools` 前，可以直接导出对象，如：
> 
> ```js
> module.exports = {
>     runtime: {
>         state: true
>     }
> }
> ```

发了一个 canary 可以试试，待充分测试后将正式发包。
`"@modern-js/app-tools": "0.0.0-canary-1641112447939"`
