### ISSUE TITLE
modern build electron 配置文件有更详细的demo能参考的么 ？

### ISSUE THREAD

**Issue by GZhiDao1010** [modern-js-dev/modern.js#435]

**Comment by spcBackToLife** [comment]
这里有比较详细的解释：https://modernjs.dev/docs/guides/features/electron/pack#%E6%9E%84%E5%BB%BA%E9%85%8D%E7%BD%AE

**Comment by spcBackToLife** [comment]
如果有其他疑问，可以再提，这个我先关了哈。
