### ISSUE TITLE
关于插件的设计以及加载方式

### ISSUE THREAD

**Issue by leeight** [modern-js-dev/modern.js#438]
例如在文件 `packages/cli/plugin-runtime/src/cli/index.ts` 中 `usePlugins` 的方式是：

```js
usePlugins([
  require.resolve('@modern-js/plugin-state/cli'),
  require.resolve('@modern-js/plugin-router/cli'),
  require.resolve('@modern-js/plugin-ssr/cli'),
]);
```

为什么不采用下面这种方式呢，把 `require.resolve` 用 `require` 代替？

```js
usePlugins([
  require('@modern-js/plugin-state/cli'),
  require('@modern-js/plugin-router/cli'),
  require('@modern-js/plugin-ssr/cli'),
]);
```

或者

```js
import state from '@modern-js/plugin-state/cli';
import router from '@modern-js/plugin-router/cli';
import ssr from '@modern-js/plugin-ssr/cli';

usePlugins([state, router, ssr]);
```

目前的这种设计方式，使用 esbuild 进行 bundle 的时候比较麻烦，不太好处理。

**Comment by await-ovo** [comment]
配置文件中 plugins 配置以及 package.json 中的插件都是指定的路径，这里 `usePlugins` 可以复用配置文件设置的插件加载、处理。
考虑到 bundle 的话，这里确实可以优化下~

**Comment by leeight** [comment]
目前插件的设计和实现方案感觉很别扭（先说问题，还没想好重构的方案）

@modern-js/core 和 @modern-js/module-tools、@modern-js/app-tools、@modern-js/monorepo-tools 的关系比较混乱。

`modern` 这个 bin 应该是 `xxx-tools` 提供的，但是实际情况下，依赖了 `@modern-js/core/bin` 的实现（这个实现最终又绕回到了各自 `xxx-tools` 里面的 build task）。

`@modern-js/core/bin` 调用了  `cli.run`（这个调用其实没有啥意义），真正发挥作用的是在 `xxx-tools` 里面又重新调用了一次 `cli.run`

以  `packages/solutions/module-tools/src/tasks/build-source-code.ts` 为例，文件最后的实现如下：

```js

(async () => {
  let options: CoreOptions | undefined;
  if (process.env.CORE_INIT_OPTION_FILE) {
    ({ options } = require(process.env.CORE_INIT_OPTION_FILE));
  }
  const { resolved } = await cli.init([], options);
  await manager.run(async () => {
    try {
      await taskMain({ modernConfig: resolved });
    } catch (e) {
      console.error(e);
    }
  });
})();
```

**Comment by await-ovo** [comment]
1. modern 这个 bin 由 xxx-tools 提供这个也是为了避免类似 「隐式依赖」  的问题，具体是在 `@modern-js/core` 里面，这个有个前提是不同的 tools 都是 `modern` 命令
2. 具体的  task 或者说命令的实现确实是在 xxx-tools 里面实现的，但是其实不需要额外调用 `cli.run` 这个方法，例子里面 `module-tools` 的例子应该是为了并行构建做的。其他的地方应该不会单独调用的~

**Comment by chenjiahan** [comment]
已在 https://github.com/modern-js-dev/modern.js/pull/741 中支持 import 加载插件，后续会逐步迁移现有代码。
