### ISSUE TITLE
降低一下目前 CI 阶段的耗时

### ISSUE THREAD

**Issue by leeight** [modern-js-dev/modern.js#445]
看了一下主要有两方面的因素导致的：
- prepare 和 test

其中 prepare 是可以省略的，test 的耗时可以集中一次性的用 jest 来代替，而不是每次执行 `modern test`。

- [x] 解决 ts alias 的问题
- [x] 使用 jest 代替 `modern test`
- [x] 删除 prepare 的过程

上述三个操作解决之后，预计 CI 阶段的耗时可以从 `30min` 降低到 `3min`。

**Comment by leeight** [comment]
> prepare为啥可以省略？之前经常遇到代码合并了 prepare跑不过导致发版之前还在修复各种问题

因为跑单测不需要编译成 CJS，直接 TS 就可以运行。

**Comment by caohuilin** [comment]
> > prepare为啥可以省略？之前经常遇到代码合并了 prepare跑不过导致发版之前还在修复各种问题
> 
> 因为跑单测不需要编译成 CJS，直接 TS 就可以运行。

跑集测还是需要的吧？整体耗时还是得等 prepare 的时间，只是相对一两个比较慢了

**Comment by leeight** [comment]
> 跑集测还是需要的吧？整体耗时还是得等 prepare 的时间，只是相对一两个比较慢了

一样的，集成测试的代码也可以直接运行，不需要走一次编译成 CJS 的过程。

**Comment by ycaptain** [comment]
modern test 底层也是基于 jest，集成了 react-testing-library，后续可能会集成 cypress 或其他方案提供 E2E 能力。如果是 jest 启动耗时，用 modern test 在更上层测可能更合适？

**Comment by caohuilin** [comment]
> > 跑集测还是需要的吧？整体耗时还是得等 prepare 的时间，只是相对一两个比较慢了
> 
> 一样的，集成测试的代码也可以直接运行，不需要走一次编译成 CJS 的过程。

那怎么保证发版时执行 prepare 生成 CJS 不会有问题呢

**Comment by leeight** [comment]
> 那怎么保证发版时执行 prepare 生成 CJS 不会有问题呢

目前 `modern test` 貌似还没这个功能。如果支持了，貌似也可以。

如果能只需要启动一次，用 `modern test` 还是 `jest` 的区别不是很大。

目前每次启动 `modern test` 的耗时比较长，大概 2s 以上，所以 100多个目录，即便没有任何测试代码要执行，也需要花费 2 分钟了。

**Comment by leeight** [comment]
> 那怎么保证发版时执行 prepare 生成 CJS 不会有问题呢

这个发版的时候单独跑一次，而不是每次 CI 的时候都去跑。

**Comment by caohuilin** [comment]
> > 那怎么保证发版时执行 prepare 生成 CJS 不会有问题呢
> 
> 这个发版的时候单独跑一次，而不是每次 CI 的时候都去跑。

感觉代码合进去之前保证正确性更合适，而不是发版的时候再发现有问题。并且代码合进去之后有问题还会影响主分支的稳定性，开发同学会被 block，这个比 CI 慢更不能接受

**Comment by leeight** [comment]
> 并且代码合进去之后有问题还会影响主分支的稳定性，开发同学会被 block，这个比 CI 慢更不能接受
`代码合进去之后有问题`，这是一个假设性的问题，我暂时没有想到合适的场景，需要给一个具体的例子来讨论。

另外有问题的代码不应该被合并进去，而是应该在 CI 的时候通过 Test Case 避免。

PS：`影响主分支的稳定性`：缺少 lock 文件，造成主分支的不稳定的事情已经持续很久了。

**Comment by caohuilin** [comment]
> > 并且代码合进去之后有问题还会影响主分支的稳定性，开发同学会被 block，这个比 CI 慢更不能接受
> 
> `代码合进去之后有问题`，这是一个假设性的问题，我暂时没有想到合适的场景，需要给一个具体的例子来讨论。
> 
> 另外有问题的代码不应该被合并进去，而是应该在 CI 的时候通过 Test Case 避免。
> 
> PS：`影响主分支的稳定性`：缺少 lock 文件，造成主分支的不稳定的事情已经持续很久了。

嗯 主分支不稳定确实很久了，所以会担心新的方案会不会有新问题，后面发版如果遇到问题我们再讨论

**Comment by leeight** [comment]
> 感觉代码合进去之前保证正确性更合适，而不是发版的时候再发现有问题。并且代码合进去之后有问题还会影响主分支的稳定性，开发同学会被 block，这个比 CI 慢更不能接受

Intergration Test 还是保持原来的方式（这个比较难改动），不过至少 Unit Test 和 Lint 比之前快了很多，有问题也能早点儿发现了。
