### ISSUE TITLE
@modern-js/module-tools和@modern-js/app-tools注册了同一个bin(modern)

### ISSUE THREAD

**Issue by hardfist** [modern-js-dev/modern.js#447]
如果我同时安装这两个，那么我启动modern dev的时候，运行的应该是哪个呢？还是说不支持同时使用这俩？

**Comment by caohuilin** [comment]
> 如果我同时安装这两个，那么我启动modern dev的时候，运行的应该是哪个呢？还是说不支持同时使用这俩？

不支持同时使用，他们是属于不同的工程方案

**Comment by hardfist** [comment]
比如我一个monorepo工程里如果同时包含这俩呢？

**Comment by caohuilin** [comment]
> 比如我一个monorepo工程里如果同时包含这俩呢？

不同的子项目里面根据工程方案用不同的 tools 就好，monorepo本身的管理使用 monorepo-tools

**Comment by hardfist** [comment]
monorepo-tools是啥，官网好像没搜到

**Comment by caohuilin** [comment]
https://github.com/modern-js-dev/modern.js/tree/main/packages/solutions/monorepo-tools

官网对于包名都没做具体介绍，希望做到不需要用户关心具体包名，当使用 @modern-js/create 创建 Monorepo 工程方案时，生成的代码中会对应的有 @modern-js/monorepo-tools 的依赖，再使用 new 命令创建子项目时，子项目中会根据对应的工程方案使用 @modern-js/app-tools 或者 @modern-js/module-tools

**Comment by hardfist** [comment]
如果确定是不支持同时使用，那可以关掉该issue了，不过文档里最好能说明下
