### ISSUE TITLE
开发 API 服务  创建项目失败 

### ISSUE THREAD

**Issue by nanzm** [modern-js-dev/modern.js#463]
运行命令失败
```shell
npx @modern-js/create api-service-demo
```

![image](https://user-images.githubusercontent.com/12454813/148713479-2cfe525f-d6f6-4cbd-a3ad-4289ba3f6424.png)

**Comment by caohuilin** [comment]
> 运行命令失败
> 
> ```shell
> npx @modern-js/create api-service-demo
> ```
> 
> ![image](https://user-images.githubusercontent.com/12454813/148713479-2cfe525f-d6f6-4cbd-a3ad-4289ba3f6424.png)

加上 --debug 参数看一下具体的错误信息
问一下 有使用 taobao 源这类国内的 npm 源吗？

**Comment by caohuilin** [comment]
https://github.com/modern-js-dev/modern.js/issues/462

**Comment by nanzm** [comment]
对的   使用了淘宝源  ``` https://registry.npmmirror.com/ ```

切回 npm 官方源 ```https://registry.npmjs.org/``` 后一切正常

🤔

**Comment by caohuilin** [comment]
> 

应该是淘宝源 npm 同步延迟问题，现在应该同步好了，你再试一下看看

**Comment by nanzm** [comment]
可以了  3Q

**Comment by duwenbin0316** [comment]
> > 
> 
> 应该是淘宝源 npm 同步延迟问题，现在应该同步好了，你再试一下看看

用 npm 官方源报同样的错了

**Comment by caohuilin** [comment]
@duwenbin0316  可能是网络问题，国内建议用 cnpm

**Comment by duwenbin0316** [comment]
> @duwenbin0316 可能是网络问题，国内建议用 cnpm

cnpm 存在同样的问题，另外搜了下其他 issue 的解决方案，清理 npx 缓存后问题依然存在

**Comment by caohuilin** [comment]
@duwenbin0316 可以加上 --debug 参数看看具体的错误信息
