### ISSUE TITLE
本地开发时，开启了 polyfill: ua 后，访问 __polyfill__，内容不符合预期

### ISSUE THREAD

**Issue by yuanlf** [modern-js-dev/modern.js#470]
本地开发时，开启了 polyfill: ua 后，访问 __polyfill__时，出现了这个提示 
![image](https://user-images.githubusercontent.com/1437018/149057573-b4a2849c-af1c-40d1-9e36-196063ce709d.png)

**Comment by zllkjc** [comment]
这个请求的 reponse 是什么呀，有完整信息截图吗

**Comment by yuanlf** [comment]
> 这个请求的 response 是什么呀，有完整信息截图吗

返回的是网页内容
![image](https://user-images.githubusercontent.com/1437018/149058212-50f5ec46-2151-4532-acac-59d60d4292ec.png)

**Comment by yuanlf** [comment]
看起来 __polyfill__ 请求被服务器 fallback 到 html 了，正常应该是内容由 web server 运行时探测 ua 后，动态下发吧

**Comment by zllkjc** [comment]
你安装一下 @modern-js/plugin-polyfill 这个插件后再尝试一下，我确认下这块功能

**Comment by yuanlf** [comment]
> @modern-js/plugin-polyfill

安装后，能符合预期，3ks
