### ISSUE TITLE
给 package.json 新增一下 publishConfig 的配置

### ISSUE THREAD

**Issue by leeight** [modern-js-dev/modern.js#481]
### 新功能详情

初步检查了一下，并不是所有的 package.json 里面都配置了。
通过 publishConfig 的配置解决的问题如下：

1. 默认情况下，把 `package.json#main` 设置为 `./src/index.ts` 从而解决在 vscode 开发时候类型找不到的问题
2. 发布版本的时候，通过 `publishConfig` 的配置把 `package.json#main` 恢复成之前的配置
3. 因为大部分 package.json 都设置了 `exports` 字段，当 `node >= 14` 的时候会忽略 `main` 这个字段，所以通过 `npm run prepare` 构建完所有模块之后，通过 CommonJS 的方式引入依然不会受到影响，还是之前的逻辑

不过按照 `3` 的表述，其实 `2` 貌似意义也不大？

**Comment by caohuilin** [comment]
> 目前发布版本的时候用的是 `npm publish` 还是 `pnpm publish`，发布版本的逻辑在哪里 @caohuilin

内部实现用的 pnpm publish，执行的根目录的 pnpm run release 命令，命令实现 https://github.com/modern-js-dev/modern.js/blob/main/packages/cli/plugin-changeset/src/commands/release.ts

**Comment by leeight** [comment]
> > 目前发布版本的时候用的是 `npm publish` 还是 `pnpm publish`，发布版本的逻辑在哪里 @caohuilin
> 
> 内部实现用的 pnpm publish，执行的根目录的 pnpm run release 命令，命令实现 https://github.com/modern-js-dev/modern.js/blob/main/packages/cli/plugin-changeset/src/commands/release.ts

如果用 pnpm 那就好， `publishConfig` 会生效。我担心如果用的是 `npm publish` 的话，就没效果了。

**Comment by leeight** [comment]
测试了一下，这个改动依赖于修正一下 `package.json` 里面对于 local package 的使用。

举个例子，在下面的改动中，把 `@modern-js/monorepo-tools` 的版本从 `"^1.0.0"` 修改为了 `"workspace:^1.2.0"`。

也就是说，之前使用的是 remote package，现在使用的是 local package

```diff
--- a/package.json
+++ b/package.json
@@ -77,10 +77,10 @@
     "babel-plugin-module-resolver": "^4.1.0",
     "@commitlint/cli": "^13.2.0",
     "@commitlint/config-conventional": "^13.2.0",
-    "@modern-js-app/eslint-config": "workspace:^1.0.0",
-    "@modern-js/eslint-config": "workspace:^1.0.0",
-    "@modern-js/monorepo-tools": "^1.0.0",
-    "@modern-js/plugin-jarvis": "workspace:^1.0.0",
-    "@modern-js/tsconfig": "workspace:^1.0.0"
+    "@modern-js-app/eslint-config": "workspace:^1.1.2",
+    "@modern-js/eslint-config": "workspace:^1.1.0",
+    "@modern-js/monorepo-tools": "workspace:^1.2.0",
+    "@modern-js/plugin-jarvis": "workspace:^1.1.1",
+    "@modern-js/tsconfig": "workspace:^1.1.0"
   }
 }
```

**Comment by leeight** [comment]
研究了一下，如果要暂时解(RAO)决(GUO)循环依赖的问题，可以考虑把 `@modern-js/plugin-testing` 用 `jest` 代替。

**Comment by hardfist** [comment]
> 的 pnpm run release 命
或许应该在发布钩子里检查下npm client是否为pnpm，
不是的话报错，防止有人错误发布
