### ISSUE TITLE
windows系统下配置了 alias 后，使用时报错了

### ISSUE THREAD

**Issue by yuanlf** [modern-js-dev/modern.js#482]
### 版本信息

```sh
@modern-js/app-tools@1.2.0
```

### 问题详情

- 在 modern.config.js 中配置了别名

alias: opts => {
      opts['@'] = './src';
    },

- 按照的方式使用：

import Header from '@/components/Header';

-  产生了如下的报错信息

![image](https://user-images.githubusercontent.com/1437018/149450389-a3501ee2-52ac-4a60-9561-f830c572c662.png)

### 问题复现

https://www.baidu.com

**Comment by yuanlf** [comment]
> ### 版本信息
> ```shell
> @modern-js/app-tools@1.2.0
> ```
> 
> ### 问题详情
> * 在 modern.config.js 中配置了别名
> 
> alias: opts => { opts['@'] = './src'; },
> 
> * 按照的方式使用：
> 
> import Header from '@/components/Header';
> 
> * 产生了如下的报错信息
> 
> ![image](https://user-images.githubusercontent.com/1437018/149450389-a3501ee2-52ac-4a60-9561-f830c572c662.png)
> 
> ### 问题复现
> https://www.baidu.com

补充说明：经测试发现，是启用了 unbundle 后才出现的问题

**Comment by chenjiahan** [comment]
Unbundled 模式暂不支持在 Windows 平台使用哈，建议在 Windows 平台下先使用非 Unbundled 模式
