### ISSUE TITLE
modern release，无法发布到私有仓库上

### ISSUE THREAD

**Issue by yulongcs** [modern-js-dev/modern.js#498]
### 新功能详情

想尝试使用modernjs, 发现无法使用 modern release 发布到私有仓库上

**Comment by caohuilin** [comment]
> ### 新功能详情
> 想尝试使用modernjs, 发现无法使用 modern release 发布到私有仓库上

设置一下 package.json 的 publishConfig，registry 设置成私有的就可以

**Comment by yulongcs** [comment]
> 
调整了registry发布还是会报错 E401
![image](https://user-images.githubusercontent.com/8512347/149862636-4631d40e-aba7-4646-8d6b-f9e81dc3f7c6.png)

**Comment by caohuilin** [comment]
包管理工具你这边使用的是 yarn 还是 pnpm?

**Comment by yulongcs** [comment]
pnpm

**Comment by caohuilin** [comment]
> pnpm

有尝试配置全局的 npm registry 为私有的路径吗？

**Comment by yulongcs** [comment]
配置了，使用nrm 使用的是私有库的地址，不行，我是用非modernjs框架就可以正常发布到私库，
很好奇为啥使用modern，release发布会到这边，Publishing to https://npm.pkg.github.com/

**Comment by caohuilin** [comment]
> 配置了，使用nrm 使用的是私有库的地址，不行，我是用非modernjs框架就可以正常发布到私库， 很好奇为啥使用modern，release发布会到这边，Publishing to https://npm.pkg.github.com/

modern  release 在非 monorepo 和 yarn 的场景下都是直接包装的 @changeset/cli 的 publish 命令，在 pnpm 的 monorepo 的场景下是直接调用的 pnpm publish 命令，我们内部也是使用的 modern release 发布的私有仓库，没遇到过 registry 的问题。

**Comment by caohuilin** [comment]
你可以尝试直接使用 @changeset/cli  publish 命令，看看问题能不能复现
