### ISSUE TITLE
wind下electron import { callMain } from '@modern-js/runtime/electron-render';报错

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [modern-js-dev/modern.js#511]
### 版本信息

```sh
- @modern-js/app-tools@1.2.0
```

### 问题详情

wind 下 electron import { callMain } from '@modern-js/runtime/electron-render';报错

```
index.js:1 loadable-components: failed to asynchronously load component Object
console.<computed> @ index.js:1
loadable.esm.js:377 Uncaught TypeError: fs.existsSync is not a function
    at getElectronPath (index.js:8)
    at Object../node_modules/electron/index.js (index.js:21)
    at Object.options.factory (react refresh:6)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
```

### 问题复现

https://codepen.io/Justineo/pen/yLbxxOR

### 初始化代码：
```typescript
import path from 'path';
import { app, Menu, Tray } from 'electron';
import Runtime, { winService } from '@modern-js/runtime/electron-main';

let tray = null;
const ico2 = path.join(__dirname, './tay.ico');
const runtime = new Runtime({
  windowsConfig: [
    {
      name: 'main',
      options: {
        width: 800,
        height: 400,
        icon: ico2,
        webPreferences: {
          contextIsolation: false,
          enableRemoteModule: true,
          webSecurity: false,
          nodeIntegration: true,
        },
      },
    },
  ],
  mainServices: {
    test: () => 'hello, modern js electron',
  },
});

app.whenReady().then(async () => {
  await runtime.init();
  const mainWindow = winService.createWindow({
    name: 'main',
    options: {
      icon: ico2,
    },
  });
 
});

```

**Comment by spcBackToLife** [comment]
如果直接在页面中使用 Node 相关 api， webpack 上需要做相应调整，将 target 改为 electron-renderer。在 modern.js 中，比较方便。只需要启动渲染进程的命令改为：
```
"dev:render": "modern dev electron-web",
```
启动主进程命令：
```
{
  "scripts": {
    "dev:main": "modern dev electron-main",
  }
}
```
详见：
https://modernjs.dev/docs/apis/commands/mwa/dev#dev-electron-web

**Comment by liuhuapiaoyuan** [comment]
> 如果直接在页面中使用 Node 相关 api， webpack 上需要做相应调整，将 target 改为 electron-renderer。在 modern.js 中，比较方便。只需要启动渲染进程的命令改为：
> 
> ```
> "dev:render": "modern dev electron-web",
> ```
> 
> 启动主进程命令：
> 
> ```
> {
>   "scripts": {
>     "dev:main": "modern dev electron-main",
>   }
> }
> ```
> 
> 详见： https://modernjs.dev/docs/apis/commands/mwa/dev#dev-electron-web

哦哦哦 没认真看callMain的实现原理，我以为只配置nodeIntegration就可以了。万分感谢

**Comment by liuhuapiaoyuan** [comment]
> 如果直接在页面中使用 Node 相关 api， webpack 上需要做相应调整，将 target 改为 electron-renderer。在 modern.js 中，比较方便。只需要启动渲染进程的命令改为：
> 
> ```
> "dev:render": "modern dev electron-web",
> ```
> 
> 启动主进程命令：
> 
> ```
> {
>   "scripts": {
>     "dev:main": "modern dev electron-main",
>   }
> }
> ```
> 
> 详见： https://modernjs.dev/docs/apis/commands/mwa/dev#dev-electron-web

@spcBackToLife 
额 我现在是dev模式下没问题，但是打包出来的release还会出现同样的问题，这是为什么》？

**Comment by spcBackToLife** [comment]
> > 如果直接在页面中使用 Node 相关 api， webpack 上需要做相应调整，将 target 改为 electron-renderer。在 modern.js 中，比较方便。只需要启动渲染进程的命令改为：
> > ```
> > "dev:render": "modern dev electron-web",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 启动主进程命令：
> > ```
> > {
> >   "scripts": {
> >     "dev:main": "modern dev electron-main",
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 详见： https://modernjs.dev/docs/apis/commands/mwa/dev#dev-electron-web
> 
> @spcBackToLife 额 我现在是dev模式下没问题，但是打包出来的release还会出现同样的问题，这是为什么》？

打包的时候同样，需要 --enableNode

详见：https://modernjs.dev/docs/apis/commands/mwa/build#build-electron

不过建议的开发方式是这样，会更好：https://modernjs.dev/docs/guides/features/electron/develop

**Comment by liuhuapiaoyuan** [comment]
嗯啊 感谢回复。解决问题了。~
