### ISSUE TITLE
开发好的API服务如何部署？

### ISSUE THREAD

**Issue by WGSHUHU** [modern-js-dev/modern.js#519]
### 版本信息

```sh
modernjs-api-service-demo@0.1.0 
└── @modern-js/app-tools@1.2.0
```

### 问题详情

直接使用modern-js-examples中的api-service项目
1. 现在使用yarn build，生成产物
2. yarn start可以运行，但是我删除src目录，yarn start运行失败，难道yarn start依赖源码src

### 问题复现

无

**Comment by zllkjc** [comment]
Duplicate of #524

**Comment by zllkjc** [comment]
这个问题我们需要修复一下，可以先把 src 放着 @yimingjfe

**Comment by yimingjfe** [comment]
这个之前 @await-ovo 评估过，要改动的地方比较多；暂时可能待先带上  src 目录，我们尽快处理下。

**Comment by yimingjfe** [comment]
测试已修复
