### ISSUE TITLE
开发API服务，热更新失效

### ISSUE THREAD

**Issue by WGSHUHU** [modern-js-dev/modern.js#522]
### 版本信息

```sh
api-service@0.1.0 
└── @modern-js/app-tools@1.2.0
```

### 问题详情

直接使用modern-js-examples中的api-service项目
1. 在api目录下增加userinfo目录，userinfo目录中新建index.ts，index.ts中写一个响应export default () => 'Hello userinfo';
2. yarn dev重新启动服务，访问http://localhost:8080/api/userinfo，响应正常
3. 修改userinfo目录下index.ts中响应的内容，服务不会重新启动

### 问题复现

无

**Comment by yimingjfe** [comment]
未复现，能再确认下吗？另外如果是 example 中的例子，热更新时，typings 中的文件重新生成了吗？

**Comment by WGSHUHU** [comment]
https://github.com/modern-js-dev/modern.js/issues/522#issuecomment-1018326572，如果直接在api目录下增加接口文件是正常的，我新建userinfo目录，在userinfo目录里面增加接口文件，热更新就会失效

**Comment by WGSHUHU** [comment]
> 未复现，能再确认下吗？另外如果是 example 中的例子，热更新时，typings 中的文件重新生成了吗？

如果直接在api目录下增加接口文件是正常的，我新建userinfo目录，在userinfo目录里面增加接口文件，热更新就会失效

**Comment by yimingjfe** [comment]
> > 未复现，能再确认下吗？另外如果是 example 中的例子，热更新时，typings 中的文件重新生成了吗？
> 
> 如果直接在api目录下增加接口文件是正常的，我新建userinfo目录，在userinfo目录里面增加接口文件，热更新就会失效

目录路径是 projectRoot -> api -> userinfo 吗？我新创建 userinfo 目录是复现不了的，能提供下 repo 吗？

**Comment by yimingjfe** [comment]
使用的是  windows 系统吗？ windows 系统下复现了

**Comment by WGSHUHU** [comment]
是的



| |
hitwgs
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年01月21日 18:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [modern-js-dev/modern.js] 开发API服务，热更新失效 (Issue #522) |

使用的是 windows 系统吗？ windows 系统下复现了

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
