### ISSUE TITLE
14.17.2版本的node不能启动api-service例子

### ISSUE THREAD

**Issue by WGSHUHU** [modern-js-dev/modern.js#523]
### 版本信息

```sh
api-service@0.1.0 
`-- @modern-js/app-tools@1.2.0
```

### 问题详情

使用modern-js-examples-main下的api-service例子
1. 将node版本切换到14.17.2，安装依赖
2. yarn dev 启动服务，报错
报错信息：
yarn run v1.22.17
warning package.json: No license field
$ modern dev
error Command failed with exit code 3221225477.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### 问题复现

无

**Comment by zllkjc** [comment]
resolutions 一下 @babel/core 到上一个版本看看，7.16.7

**Comment by WGSHUHU** [comment]
> resolutions 一下 @babel/core 到上一个版本看看，7.16.7
将@babel/core resolutions  到7.16.7就好了，是因为@babel/core新版本有问题是吗？

**Comment by yimingjfe** [comment]
特定 babel/core 版本（7.16.10）问题，新版  babel/core 已无此问题。
