### ISSUE TITLE
开发API服务失败

### ISSUE THREAD

**Issue by WGSHUHU** [modern-js-dev/modern.js#524]
### 版本信息

```sh
modernjs-api-service-demo@0.1.0 
└── @modern-js/app-tools@1.2.0
```

### 问题详情

按照官网https://modernjs.dev/docs/start/api-service
1.  创建API服务，删除“src”目录，然后启动yarn dev，报错

### 问题复现

无

**Comment by yimingjfe** [comment]
测试已修复
