### ISSUE TITLE
使用@modern-js/create 创建项目时，没有生成 modern.config.js 文件

### ISSUE THREAD

**Issue by WGSHUHU** [modern-js-dev/modern.js#526]
### 版本信息

```sh
modernjs-api-service-demo@0.1.0 
└── @modern-js/app-tools@1.2.0
```

### 问题详情

https://modernjs.dev/docs/apis/hooks/module/modern-config
使用@modern-js/create 创建项目时，并没有生成 modern.config.js 文件。

### 问题复现

无

**Comment by zllkjc** [comment]
这个是符合预期的

**Comment by caohuilin** [comment]
现在默认不会生成 modern.config.js，推荐用户简单的配置通过 package.json 的 modernConfig 去设置，文档问题需要修复一下

**Comment by leeight** [comment]
其实我感觉用 modern.config.js 或者 modern.config.ts 更合适一些，放到 package.json 里面不太合适。

放到独立的文件里面，可以有类型提示。

**Comment by caohuilin** [comment]
> 其实我感觉用 modern.config.js 或者 modern.config.ts 更合适一些，放到 package.json 里面不太合适。
> 
> 放到独立的文件里面，可以有类型提示。

放到 package.json 中的上下文是 json 比较好使用代码进行编辑和处理，在低码平台上可以更好的集成。

**Comment by leeight** [comment]
JSON 编辑是更容易出错的，多一个逗号就挂了。
为了考虑未来低码的需求，目前的体验方面其实并不太好。

**Comment by chenjiahan** [comment]
JSON 能承载的逻辑比较有限，比如无法使用 `tools.webpack` 这种函数类型的字段。

在实际业务中，大部分是需要通过 `modern.config.ts` 去配置一些字段的，在模板中内置此文件会对开发同学更加友好。
