### ISSUE TITLE
electron开发，build的时候package.json的依赖丢失

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [modern-js-dev/modern.js#529]
### 版本信息

```sh
@modern-js/app-tools@1.2.0
```

### 问题详情

很奇怪明明安装好的依赖，就因为在electron/mian.js中没有直接依赖，就无法生成到dist/package.json中，我这边是要通过electron管理一个由midwayjs生成的项目，而那个项目在单独的server目录中，server目录通过配置可以拷贝到安装资源中，但是他的相关依赖就过不来，这怎么办呢？

### 问题复现

https://codepen.io/Justineo/pen/yLbxxOR

**Comment by spcBackToLife** [comment]
抱歉久等啦，未能及时回复。我看问题复线的连接点过去没东西。可否给一个 github demo 地址，来看看你的场景。
- 关于依赖可以主动配置。
- 关于主进程中如何引用其他目录并构建，也可配置。
但文档还欠缺，我这就补上。

**Comment by liuhuapiaoyuan** [comment]
o  sorry  很久没来看了。我现在在server中直接import来解决了这个问题

**Comment by liuhuapiaoyuan** [comment]
如果有文档就更好了
