### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by WGSHUHU** [modern-js-dev/modern.js#531]
### 版本信息

```sh
@modern-js/app-tools@1.2.0
```

### 问题详情

@modern-js/create创建一个项目，将该项目放到一个空文件夹(demo)中，使用vscode打开项目代码出现eslint报错

Parsing error: Cannot read file 'c:\users\xxxxxx\modern-js-examples-main\tsconfig.json'.eslint

复现路径：直接打开modern-js-examples-main项目中quick-start中的micro-frontend项目中mian文件夹下的src目录下的App.tsx，第一行import前面会有一个eslint报错

平台：windows

### 问题复现

无

**Comment by caohuilin** [comment]
最新版已修复
