### ISSUE TITLE
开启Unbundled 开发模式后，页面空白，控制台报错

### ISSUE THREAD

**Issue by henryzp** [modern-js-dev/modern.js#533]
### 版本信息

```sh
@modern-js/app-tools@1.3.0
```

### 问题详情

用https://modernjs.dev/docs/start/website
的快速入门指南，创建了一个应用

在不开启Unbundled模式，yarn dev，可以打开页面，且页面正常

开启后，页面一片空白，控制台报错

![image](https://user-images.githubusercontent.com/3849702/150907185-5be6d6be-3160-44c0-9a16-328ff74c4f0c.png)

一开始以为pnpm的问题，后移除依赖包，用yarn重新安装，也是一样的结果。

### 问题复现

无

**Comment by chenjiahan** [comment]
你好，我这边试了下开启 unbundle 模式是可以正常运行页面的，这个 issue 先 close 了哈。

如果你这边还存在问题，麻烦提供一个最小复现仓库，我们会跟进排查。
