### ISSUE TITLE
library-project 项目 yarn error

### ISSUE THREAD

**Issue by WGSHUHU** [modern-js-dev/modern.js#534]
### 版本信息

```sh
@modern-js/app-tools@1.2.0
```

### 问题详情

直接打开modern-js-examples-main项目中quick-start中的library-project项目，进行yarn，报错，报错信息如下

node_modules/@modern-js/core/src/config/index.ts(4,20): error TS7016: Could not find a declaration file for module 'signale'. 'C:/xxx/workspace/modern-js-examples-main/quick-start/library-project/node_modules/signale/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/signale` if it exists or add a new declaration (.d.ts) file containing `declare module 'signale';`
node_modules/@modern-js/core/src/config/index.ts(13,23): error TS7016: Could not find a declaration file for module 'lodash.mergewith'. 'C:/xxx/workspace/modern-js-examples-main/quick-start/library-project/node_modules/lodash.mergewith/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/lodash.mergewith` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash.mergewith';`
node_modules/@modern-js/core/src/config/index.ts(15,34): error TS7016: Could not find a declaration file for module '@babel/code-frame'. 'C:/xxx/workspace/modern-js-examples-main/quick-start/library-project/node_modules/@babel/code-frame/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/babel__code-frame` if it exists or add a new declaration (.d.ts) file containing `declare module '@babel/code-frame';`
node_modules/@modern-js/core/src/config/mergeConfig.ts(1,23): error TS7016: Could not find a declaration file for module 'lodash.mergewith'. 'C:/xxx/workspace/modern-js-examples-main/quick-start/library-project/node_modules/lodash.mergewithtion file for module 'lodash.mergewith'. 'C:/xxx/workspace/modern-js-examples-main/quick-start/library-project/node_modules/lodash.mergewith/index.js' implicitly has an 'any' type.           containing `declare module 'lodash.mergewith';`
  Try `npm i --save-dev @types/lodash.mergewith` if it exists or add a new declaration (.d.ts) file ation file for module 'lodash.clonedeep'. 'C:/xxx/workspace/modern-js-examples-main/quick-start/library-project/node_modules/lodash.clonedee
containing `declare module 'lodash.mergewith';`
node_modules/@modern-js/core/src/config/schema/index.ts(3,23): error TS7016: Could not find a declarcontaining `declare module 'lodash.clonedeep';`
not find a declaration file for module 'lodash.clonedeep'. 'C:/xxx/workspaples-main/quick-sce/modern-js-examples-main/quick-start/library-project/node_modules/lodash.clonedee' type.p/index.js' implicitly has an 'any' type.                                          ion (.d.ts) file
  Try `npm i --save-dev @types/lodash.clonedeep` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash.clonedeep';`
  
  平台：windows

### 问题复现

无

**Comment by caohuilin** [comment]
已修复 example
