### ISSUE TITLE
library-project 项目中的storybook的 docs.source.type = 'code' not available

### ISSUE THREAD

**Issue by WGSHUHU** [modern-js-dev/modern.js#535]
### 版本信息

```sh
@modern-js/app-tools@1.2.0
```

### 问题详情

直接打开modern-js-examples-main项目中quick-start中的library-project项目中stories文件夹下的index.stories.tsx，添加
`YoursStory.parameters = {
   docs: {
      source: {
           type: 'code'
     } 
  }
}`

页面显示 No code available

### 问题复现

无

**Comment by targeral** [comment]
你可以尝试一下最新的版本：@modern-js/module-tools@1.6.3。

我按照你说的方式尝试了一下，没有出现这个问题了。
