### ISSUE TITLE
library-project项目发布失败

### ISSUE THREAD

**Issue by WGSHUHU** [modern-js-dev/modern.js#536]
### 版本信息

```sh
@modern-js/app-tools@1.2.0
```

### 问题详情

1.  直接打开modern-js-examples-main项目中quick-start中的library-project项目，安装依赖，执行yarn release，报错，报错信息如下
error parsing json:
�  error SyntaxError: Unexpected end of JSON input
�  error     at JSON.parse (<anonymous>)

平台：windows

### 问题复现

无

**Comment by caohuilin** [comment]
在 library-project 下面执行一下  pnpm publish --json --access public --tag latest --no-git-checks 可以看到具体的错误信息

changeset 这里直接对 stdout 做了 JSON.parse，当有错误时，这里会挂掉，需要跟进一下 changeset 这边的修复

**Comment by htscwgs** [comment]
> 在 library-project 下面执行一下 pnpm publish --json --access public --tag latest --no-git-checks 可以看到具体的错误信息
> 
> changeset 这里直接对 stdout 做了 JSON.parse，当有错误时，这里会挂掉，需要跟进一下 changeset 这边的修复

可以发布了，原本用户使用‘npm publish’就可以发布并且看到详细的报错，为什么官网还要使用“pnpm run release”(关键它不给详细错误信息)包一下publish操作？

**Comment by caohuilin** [comment]
模块工程方案的发版方案使用了 changeset ，方便统一处理单独项目和 monorepo 的场景，在单独的模块项目中，npm publish 仍然是适用的。
changeset 的问题我们跟进一下，暂时可以先通过上面的命令定位问题

**Comment by caohuilin** [comment]
关联 issue： https://github.com/changesets/changesets/issues/338

**Comment by leohxj** [comment]
是否有 verbose 参数, 可以查看更多日志信息
