### ISSUE TITLE
Module '"@modern-js/runtime/testing"' has no exported member 'screen'.

### ISSUE THREAD

**Issue by WGSHUHU** [modern-js-dev/modern.js#538]
### 版本信息

```sh
(empty)
```

### 问题详情

使用@modern-js/create来开发UI组件，测试目录tests下的index.test.tsx中显示 Module '"@modern-js/runtime/testing"' has no exported member 'render'
1. 安装@modern-js/runtime之后，在node_modules中找到@modern-js/runtime包，发现没有testing文件
2. 运行yarn test，测试用例显示都通过了，在node_modules中找不到@modern-js/runtime/testing文件，不应该失败吗？

### 问题复现

无

**Comment by caohuilin** [comment]
@modern-js/runtime/testing 的路径是 @modern-js/plugin-testing 插件动态提供的，对应的类型定义在 @modern-js/plugin-testing/type 中，可以确认一下 tests/modern-app-env.ts 中是否包含  `///<reference types="@modern-js/plugin-testing/type" />` 这个是用来提示类型的

**Comment by WGSHUHU** [comment]
> @modern-js/runtime/testing 的路径是 @modern-js/plugin-testing 插件动态提供的，对应的类型定义在 @modern-js/plugin-testing/type 中，可以确认一下 tests/modern-app-env.ts 中是否包含 `///<reference types="@modern-js/plugin-testing/type" />` 这个是用来提示类型的

1. 是有的，但是我通过vscode直接点击看类型文件，并没有到@modern-js/plugin-testing目录下，而是到了@modern-js/module-tools中(它里面声明的是一个空对象)

**Comment by yimingjfe** [comment]
使用 mac 和  windows 都未复现这个问题；重启 ts server 试下呢？vscode 中 cmd(ctrl) + shift + p， 输入 restart ts server。

**Comment by WGSHUHU** [comment]
> 使用 mac 和 windows 都未复现这个问题；重启 ts server 试下呢？vscode 中 cmd(ctrl) + shift + p， 输入 restart ts server。

windows下面使用vscode直接打开modern-js-examples-main项目中quick-start中的components-project项目中的tests下的index.test.tsx，就可以看到

**Comment by caohuilin** [comment]
已修复，example 也已更新
