### ISSUE TITLE
请问支持自己添加自定义loader吗，如，打包svg图标。或者官方直接添加svg图标这种常见的需求？

### ISSUE THREAD

**Issue by daigang666** [modern-js-dev/modern.js#542]
### 新功能详情

请问支持自己添加自定义loader吗，如，打包svg图标。或者官方直接添加svg图标这种常见的需求？

**Comment by rqzheng2015** [comment]
修改配置[tools.webpack](https://modernjs.dev/docs/apis/config/tools/webpack)即可实现webpack配置修改，自定义loader也能实现

**Comment by daigang666** [comment]
实话，完全没看明白如何修改配置，或者自己配置Loader，并且右上角的搜索完全不可用

**Comment by zllkjc** [comment]
https://modernjs.dev/docs/guides/usages/debug/unbundled#js-%E4%B8%AD%E4%BD%BF%E7%94%A8-svg
Svg 功能是支持的

**Comment by daigang666** [comment]
我试试，顺便，头像好评。

**Comment by chenjiahan** [comment]
@daigang666 以下是一个自定义 loader 的示例：
```js
// modern.config.js
import { defineConfig } from '@modern-js/app-tools';

export default defineConfig({
  tools: {
    webpack: (config, { chain }) => {
      chain.module
        .rule('compile-svg')
        .test(/\.svg$/)
        .use('svg-inline')
        .loader('svg-inline-loader');
    },
  },
});
```

完整 API 可以参考 webpack-chain 文档：https://github.com/neutrinojs/webpack-chain。

后续我们会在文档中补充一些类似的例子。
