### ISSUE TITLE
node_modules/@modern-js/runtime-core/src/loader/useLoader.ts(22,5): error TS271

### ISSUE THREAD

**Issue by WGSHUHU** [modern-js-dev/modern.js#543]
### 版本信息

```sh
@modern-js/app-tools@1.2.0
```

### 问题详情

直接打开modern-js-examples-main项目中quick-start中的components-project项目，运行yarn 安装依赖，报错，报错信息如下：

node_modules/@modern-js/runtime-core/src/loader/useLoader.ts(22,5): error TS2717: Subsequent property declarations must have the same type.  Property '_SSR_DATA' must be of type 'SSRContainer | undefined', but here has type 'SSRContainer | undefined'.

### 问题复现

无

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/155479143-0fcf25f7-d240-4a97-94bb-4ab4e48424e7.png)

未复现此问题，建议删除 node_modules 重新安装试下
