### ISSUE TITLE
API服务部署虚拟机报错

### ISSUE THREAD

**Issue by WGSHUHU** [modern-js-dev/modern.js#551]
### 版本信息

```sh
@modern-js/app-tools@1.3.0
```

### 问题详情

1. 将本地开发好的API服务，部署到虚拟机，使用yarn start命令，出现以下报错
     一：Cannot find module '@modern-js/core/bin'
     原因：源码引入的时候少写了具体执行文件的名字
     解决：修改node_modules/.bin/modern为require('@modern-js/core/bin/modern-js.js')
    二：loading config file modern.config.js报错，is not function
     原因：modern.config.js中写的是module.exports = {}
     解决：删除modern.config.js，在package.json的modernConfig中进行配置
    三：Can not find plugin @modern-js/app-tools/cli，这个怎么解决？
 

### 问题复现

无

**Comment by yimingjfe** [comment]
虚拟机的系统也是 windows 吗？

**Comment by leeight** [comment]
部署的过程是怎么操作的？

**Comment by WGSHUHU** [comment]
> 虚拟机的系统也是 windows 吗？

Linux

**Comment by WGSHUHU** [comment]
> 部署的过程是怎么操作的？

1. 跑CI，进行build
2. 然后将api目录、dist目录、node_modules目录、src目录、package.json、modern.config.js、tsconfig.json上传到虚拟机的某个目录中
3. 在虚拟机上运行 npm run start，就报错了

**Comment by WGSHUHU** [comment]
> 虚拟机的系统也是 windows 吗？

通过升级node版本解决了问题，虚拟机上的版本有点低（不支持exports，http://nodejs.cn/api/packages/exports.html）
