### ISSUE TITLE
按模板生成的electron应用缺少test命令

### ISSUE THREAD

**Issue by ascodelife** [modern-js-dev/modern.js#559]
### 版本信息

```sh
├── @modern-js/app-tools@1.3.1 -> .\node_modules\.pnpm\@modern-js+app-tools@1.3.1_typescript@4.5.5\node_modules\@modern-js\app-tools
└─┬ @modern-js/plugin-electron@1.0.15 -> .\node_modules\.pnpm\@modern-js+plugin-electron@1.0.15_9d741c1e61e4000586c68f5e4ff4dde9\node_modules\@modern-js\plugin-electron
  └── @modern-js/app-tools@1.3.1 -> .\node_modules\.pnpm\@modern-js+app-tools@1.3.1_typescript@4.5.5\node_modules\@modern-js\app-tools
```

### 问题详情

在文档中给出了electron的测试命令pnpm run test
https://modernjs.dev/docs/guides/features/electron/test#运行测试
但是在按照提供的模板起electron项目后没有发现package.json下有test命令
https://modernjs.dev/docs/start/electron

### 问题复现

https://github.com/ascodelife/electron-demo

**Comment by spcBackToLife** [comment]
项目下执行 yarn new 启用测试功能即可：

![image](https://user-images.githubusercontent.com/20703494/151274647-7b2b033d-52cd-42dc-bebe-c428fc02c6d9.png)
