### ISSUE TITLE
modern test单元测试功能能否提供更细粒度的控制

### ISSUE THREAD

**Issue by ascodelife** [modern-js-dev/modern.js#561]
### 新功能详情

https://modernjs.dev/docs/apis/commands/module/test
modernjs提供了modern test的单测命令，但是每次运行命令都会重新执行src目录下的所有单测，无法精确到某个文件某个测试用例。另一方面，modernjs集成的test功能虽然是基于jest开发的，但是没法配合一些jest插件来使用。所以，modernjs提供test功能模块的目的仅仅是提供了一个统一跑测试用例的入口？

**Comment by caohuilin** [comment]
test 支持 jest 的所有命令的，直接 modern test + 文件名就可以单独执行某一个文件的测试用例

package.json 中 test 命令加了 --passWithNoTests 导致后面加文件名的行为会失效，需要更新一下生成项目的模板文件，下个版本会修复

jest 的配置也支持的：https://modernjs.dev/docs/apis/config/tools/jest

**Comment by ascodelife** [comment]
> test 支持 jest 的所有命令的，直接 modern test + 文件名就可以单独执行某一个文件的测试用例
> 
> package.json 中 test 命令加了 --passWithNoTests 导致后面加文件名的行为会失效，需要更新一下生成项目的模板文件，下个版本会修复
> 
> jest 的配置也支持的：https://modernjs.dev/docs/apis/config/tools/jest

感谢回复。现在所用的vscode的jest插件提供了快捷的jest命令执行，这类插件需要去找node_modules下顶层的jest库，即`\node_modules\jest\bin\jest.js`，但是由于Modernjs把jest库隐藏到更深的层级了，导致这类插件失效了，有没有考虑提供类似`react-scripts eject`的命令把把jest暴露出来，使得能正常兼容jest插件。

**Comment by caohuilin** [comment]
可以现在 .npmrc 中设置 public-hoist-pattern[]=jest 将 jest 依赖提高到顶层依赖

**Comment by ascodelife** [comment]
> 可以在 .npmrc 中设置 public-hoist-pattern[]=jest 将 jest 依赖提高到顶层依赖

it works！
