### ISSUE TITLE
开发工具库时，创建 Monorepo过程中依赖包缺少报错

### ISSUE THREAD

**Issue by xushuailing** [modern-js-dev/modern.js#562]
### 版本信息

```sh
monorepo@ /Users/xxx/tools/tool-tuils-modern
└── @modern-js/app-tools@1.3.0  -> /Users/xxx/tools/tool-tuils-modern/node_modules/.pnpm/@modern-js+app-tools@1.3.0/node_modules/@modern-js/app-tools

❯ node -v                    
v14.18.1

❯ pnpm -v   
6.20.3
```

### 问题详情

https://modernjs.dev/docs/start/library#%E5%88%9B%E5%BB%BA-monorepo

根据文档说明，一步一步往下做，出现依赖包安装失败 

![middle_img_v2_70774346-2da7-43c2-a6f5-2743e8809ceg](https://user-images.githubusercontent.com/25056086/151306532-d1811754-8c18-40d1-953b-a2f2b6d8177d.png)

![PC15a1C5Sl](https://user-images.githubusercontent.com/25056086/151306431-f25ccf70-61b7-4956-bb78-f1cfae85db87.png)

需要手动安装一下类型声明包才能消除报错信息
![middle_img_v2_2673c948-1701-4a74-8946-99e8dd3217cg](https://user-images.githubusercontent.com/25056086/151306468-a1d0e0bb-c4e8-4368-8d3a-79447633e8f8.png)

### 问题复现

https://codepen.io/Justineo/pen/yLbxxOR

**Comment by targeral** [comment]
辛苦给一下创建的子项目所依赖的 @modern-js/module-tools 的版本（可以通过直接查看 `'子项目目录/node_modules/@modern-js/module-tools/package.json'` 文件)以及检查一下创建的子项目目录下的 `src/modern-app-env.d.ts` 文件内容是否是和下面一致：

```
/// <reference types='@modern-js/module-tools/type' />
/// <reference types='@modern-js/plugin-testing/type' />
```

❤️
