### ISSUE TITLE
server-plugin 没有生效

### ISSUE THREAD

**Issue by nervouself** [modern-js-dev/modern.js#563]
### 版本信息

```sh
@modern-js/app-tools/1.3.1
```

### 问题详情

创建 server-plugin，在 modern config 引入以后没有生效

步骤：
npx @modern-js/create
pnpm i @modern-js/server-plugin
添加插件并配置
pnpm dev

最小可复现代码
[modern-test.zip](https://github.com/modern-js-dev/modern.js/files/7948781/modern-test.zip)

### 问题复现

见问题详情附件

**Comment by zllkjc** [comment]
这样可能会出现多个 server-plugin 的实例，尝试用 peerDependencies 试试

**Comment by nervouself** [comment]
我用的其他 monorepo 工具，完全隔绝影子依赖😂用 peerDependencies 编译不通过

**Comment by nervouself** [comment]
我试了下，preServerInit 这个 hook 可以，prepareWebServer 这个就不行

**Comment by nervouself** [comment]
目前升级后 modern-config 里的 server-plugin 失效了

**Comment by yimingjfe** [comment]
> 目前升级后 modern-config 里的 server-plugin 失效了

在项目根目录新建 `modern.server-runtime.config.ts` 文件，把插件的使用放在这个文件中，格式和 `modern.config.ts` 是一致的。

**Comment by nervouself** [comment]
实测 prepareApiServer 没生效，之前老写法的 preServerInit 现在也不支持了，请问下把哪几个包回退到哪个版本可以解决？

**Comment by nervouself** [comment]
> 可以使用 beforeProdServer 这个钩子，就是原来的 preServerInit 改名字了
这个好使了😭
