### ISSUE TITLE
monorepo-generator package test error

### ISSUE THREAD

**Issue by caohuilin** [modern-js-dev/modern.js#577]
### 版本信息

```sh
@modern-js/plugin-i18n 1.2.1
```

### 问题详情

更新仓库 @modern-js/plugin-i18n 版本号为 1.2.1，更新方式可以在根目录 `package.json` 中增加 `resolutions` 字段
```json
  "resolutions": {
    "@modern-js/plugin-i18n": "1.2.1"
  }
```

安装依赖后，进入 `packages/generator/generators/monorepo-generator` 执行 `pnpm run test` 命令报错，报错信息如下：
![image](https://user-images.githubusercontent.com/12605189/151648157-7b20d80e-7216-4ed3-907c-572eb9f1240e.png)

调试发现是 jest resolve 模块时报错。

简单复现场景：在根目录新建 `node.js` 文件，内容如下:
```
const resolver = require('./jest.resolver.js');

resolver('@modern-js/plugin-i18n', {
  basedir: './node_modules/.pnpm/@modern-js+codesmith-api-app@1.0.7/',
});

``` 

执行 `node node.js` 出现下面报错：
![image](https://user-images.githubusercontent.com/12605189/151648251-d4def8a6-82a6-47e7-b504-38cbfbd1272d.png)

删除 `node_modules/.pnpm/@modern-js+codesmith-api-app@1.0.7/node_modules/@modern-js/plugin-i18n/package.json` 下的 exports 下的 `jsnext:source` 字段后，可修复该问题。
![image](https://user-images.githubusercontent.com/12605189/151648274-3655ec13-f7e9-40e6-a5c7-da29019ca340.png)

问题： 为什么 jsnext:source 字段会影响 resolve 逻辑？

### 问题复现

无

**Comment by caohuilin** [comment]
临时解决方案，配置 plugin-i18n package 的 publishConfig，发布版本时去除 export 下的 `jsnext:source` 字段

https://github.com/modern-js-dev/modern.js/pull/576/commits/93c7d25e22e419e73f68303a110ae15861f01086

**Comment by leeight** [comment]
上面的测试逻辑用到了 `const resolver = require('./jest.resolver.js');`，这里配置了 `'jsnext:source' 所以貌似也是合理的

```
const enhanceResolve = require('enhanced-resolve');

const resolver = enhanceResolve.create.sync({
  conditionNames: ['jsnext:source', 'require', 'node', 'default'],
  extensions: ['.js', '.json', '.node', '.ts', '.tsx'],
});

module.exports = function (request, options) {
  return resolver(options.basedir, request);
};
```

**Comment by caohuilin** [comment]
应该还和昨天发版有关系，@modern-js/plugin-i18n 1.2.1 把  src 目录加入了 .npmignore(https://github.com/modern-js-dev/modern.js/pull/566), 正式版本中将不再包含 src 文件夹。

**Comment by leeight** [comment]
我执行如下的操作：

```
mkdir tmp
cd tmp && npm init -y
pnpm add @modern-js/plugin-i18n
node -e 'console.log(require("@modern-js/plugin-i18n"))'
```

貌似是正常的

**Comment by caohuilin** [comment]
> 我执行如下的操作：
> 
> ```
> mkdir tmp
> cd tmp && npm init -y
> pnpm add @modern-js/plugin-i18n
> node -e 'console.log(require("@modern-js/plugin-i18n"))'
> ```
> 
> 貌似是正常的

是的 ，不影响正常 require

**Comment by leeight** [comment]
所以你上面的问题其实不是问题：

> 问题： 为什么 jsnext:source 字段会影响 resolve 逻辑？

本来就是想要 `jest.resolver.js` 配合 `jsnext:source` 来影响 resolve 的逻辑的。
根目录执行 `npm run test:ut` 的时候，有这个参数 `node --conditions=jsnext:source`

**Comment by caohuilin** [comment]
因为 `@modern-js/codesmith-api-app` 依赖了 `@modern-js/plugin-i18n` 这个包，`@modern-js/codesmith-api-app` 是个外部依赖，对应 `@modern-js/plugin-i18n` 也对应是个外部依赖(不是 workspace 的软链)，`jest.resolver.js` 这时不应该对外部依赖生效

**Comment by leeight** [comment]
> jest.resolver.js 这时不应该对外部依赖生效

想不到太好的办法去判断是不是一个外部的依赖，因为 `@modern-js/plugin-i18n` 的确是一个 workspace 下面的 local package。

感觉最简单的做法是把 `@modern-js/codesmith-api-app` 也放到仓库里面就没这个问题了。
