### ISSUE TITLE
按照文档不能正确的开启electron node集成

### ISSUE THREAD

**Issue by ascodelife** [modern-js-dev/modern.js#586]
### 版本信息

```sh
├── @modern-js/app-tools@1.3.1 -> .\node_modules\.pnpm\@modern-js+app-tools@1.3.1_esbuild@0.14.14+typescript@4.5.5\node_modules\@modern-js\app-tools
└─┬ @modern-js/plugin-electron@1.0.15 -> .\node_modules\.pnpm\@modern-js+plugin-electron@1.0.15_9d741c1e61e4000586c68f5e4ff4dde9\node_modules\@modern-js\plugin-electron
  └── @modern-js/app-tools@1.3.1 -> .\node_modules\.pnpm\@modern-js+app-tools@1.3.1_esbuild@0.14.14+typescript@4.5.5\node_modules\@modern-js\app-tools
```

### 问题详情

1. 模块引入路径问题
文档一共在两处提及了如何通过预加载去集成node，分别为
a.https://modernjs.dev/docs/guides/features/electron/develop#%E7%AA%97%E5%8F%A3%E4%B8%AD%E5%85%B3%E9%97%AD-node%E6%8E%A8%E8%8D%90
b.https://modernjs.dev/docs/start/electron#%E6%96%B0%E5%BB%BA%E9%A2%84%E5%8A%A0%E8%BD%BD%E8%84%9A%E6%9C%AC%E7%9B%AE%E5%BD%95
这两处的electron/preload/index.dev.js内容有一些差异，差异点在于从何处引入babelConfig，经过测试a有误b正确
2. 按照文档配置后依然有误
控制台报错
![image](https://user-images.githubusercontent.com/26686921/152633513-29f0299d-22de-4481-9ab5-43fb28c8b0b4.png)
渲染进程中引入`import bridge from "@modern-js/runtime/electron-bridge";`
打印`bridge`为`undefined`
按照控制台提示在electron/main.ts中修改为
```
const runtime = new Runtime({
  windowsConfig: [
    {
      name: "main",
      options: {
        webPreferences: {
          enableRemoteModule: true, // 新增enableRemoteModule

          preload: PRELOAD_JS,
        },
      },
    },
  ],
  mainServices: {
    test: () => "hello, modern js electron",
  },
})
```
此时窗体白屏 控制台显示
![image](https://user-images.githubusercontent.com/26686921/152633483-2cd949a7-beff-4e16-82b5-de2f99a27c8a.png)

启动命令为：`"dev:electron": "modern dev electron"`

感谢你们的帮助。

### 问题复现

无

**Comment by spcBackToLife** [comment]
没有例子，所以我新建一个项目试试：
![image](https://user-images.githubusercontent.com/20703494/153157558-5197fd57-3edf-40d9-8059-4c7fe30e32fe.png)
![image](https://user-images.githubusercontent.com/20703494/153157646-830df2ba-e8e0-4f3f-ac7b-6eaa93976948.png)

然后我按照这个例子：https://modernjs.dev/docs/guides/features/electron/develop#%E7%AA%97%E5%8F%A3%E4%B8%AD%E5%85%B3%E9%97%AD-node%E6%8E%A8%E8%8D%90

添加：
![image](https://user-images.githubusercontent.com/20703494/153157899-4871f778-c378-439d-bfa0-f90145fddbbc.png)

![image](https://user-images.githubusercontent.com/20703494/153157963-6225b9f3-f3c2-4a74-acd5-feb43f369fe0.png)

修改 main.ts

![image](https://user-images.githubusercontent.com/20703494/153158198-42197a66-5959-4e22-81e8-228ae5fd5d23.png)

此时要注意，我现在 electron 是 13 因此要加上：contextIsolation: false。可能是这个导致的白屏哟。

我现在启动：
![image](https://user-images.githubusercontent.com/20703494/153158454-29e304c7-b367-4bfe-8779-b74656778f7e.png)

成功啦，我再渲染进程里访问下 test 服务。
![image](https://user-images.githubusercontent.com/20703494/153158761-048f5cd0-5e2d-47fa-9a4c-834212ab04f8.png)

确实报了  Cannot read property 'callMain' of undefined。

emmm，看了下调试工具台：

![image](https://user-images.githubusercontent.com/20703494/153158957-a43a381c-a63a-4023-bf92-6dde09b87e20.png)

应该是文档 demo 给错了，这样改 index.dev.js:
![image](https://user-images.githubusercontent.com/20703494/153159085-5b5f7d7b-cda2-4cca-938f-11a5d119852d.png)

重新启动可以啦！
![image](https://user-images.githubusercontent.com/20703494/153159194-26188164-8e59-4b95-8c5d-862451e4ab32.png)


## 总结

我的锅，文档没搞好，我改改！
