### ISSUE TITLE
electron services不能如预期一样工作

### ISSUE THREAD

**Issue by ascodelife** [modern-js-dev/modern.js#589]
### 版本信息

```sh
├── @modern-js/app-tools@1.3.1 -> .\node_modules\.pnpm\@modern-js+app-tools@1.3.1_esbuild@0.14.14+typescript@4.5.5\node_modules\@modern-js\app-tools
└─┬ @modern-js/plugin-electron@1.0.15 -> .\node_modules\.pnpm\@modern-js+plugin-electron@1.0.15_9d741c1e61e4000586c68f5e4ff4dde9\node_modules\@modern-js\plugin-electron
  └── @modern-js/app-tools@1.3.1 -> .\node_modules\.pnpm\@modern-js+app-tools@1.3.1_esbuild@0.14.14+typescript@4.5.5\node_modules\@modern-js\app-tools
```

### 问题详情

按照文档 https://modernjs.dev/docs/guides/features/electron/ipc/regist-services/main 去使用Modernjs封装的上层通信服务时，在渲染进程出现了报错。
![image](https://user-images.githubusercontent.com/26686921/152691385-0bca90a6-30ff-4f3a-980b-5cbd634769d5.png)

由于Modernjs封装的上层通信服务是基于ipcmain和ipcrenderer封装的，因此我提供了可能与之相关的issue见 https://github.com/electron/electron/issues/7300
为了更进一步说明，附上一个便于复现的项目地址。

### 问题复现

https://github.com/ascodelife/electron-service-test

**Comment by spcBackToLife** [comment]
看你在代码中直接使用了 api:
![image](https://user-images.githubusercontent.com/20703494/153159672-a6d1c1b2-04de-4155-8dad-5d45970c8acd.png)

因此，参考：
https://modernjs.dev/docs/guides/features/electron/develop#%E7%AA%97%E5%8F%A3%E4%B8%AD%E5%BC%80%E5%90%AF-node
这个文档。可以这样修改启动命令，或者在命令文档中这样：
![image](https://user-images.githubusercontent.com/20703494/153159898-a45a6283-8314-4a8f-8802-cbc282115c6a.png)

**Comment by chenjiahan** [comment]
感谢反馈，我们会持续优化文档的组织方式和关联内容~
