### ISSUE TITLE
[Bug]: 开启disableCssModuleExtension配置后，后台报错

### ISSUE THREAD

**Issue by yerled** [modern-js-dev/modern.js#629]
### 版本信息

```sh
whale2@2.0.0 /Users/yerled/Documents/yuanguanglong/whale2
└── @modern-js/app-tools@1.4.0
```

### 问题详情

`export default defineConfig({
  dev: {
    proxy: './proxy.ts',
  } as DevConfig,
  output: {
    disableCssModuleExtension: true,
  },
});`

css modules，开启disableCssModuleExtension配置后，后台报错。

![image](https://user-images.githubusercontent.com/13483247/154219325-4d8b2fd4-6436-431d-ac82-96abf6936ad6.png)

### 问题复现

暂无

**Comment by chenjiahan** [comment]
@yerled 我尝试了下未复现此问题。

从你提供的报错信息上看，可能是项目中的 Less 支持未正确启用，建议通过 `new` 命令启用「Less 支持」。

如果确定项目中的 Less 支持已开启，并且仍能复现此问题，麻烦提供一下复现该问题的仓库，便于我们进一步排查。

**Comment by yerled** [comment]
@chenjiahan 你好，我补充了可以复现这个问题的demo： [disableCssModuleExtension问题](https://github.com/yerled/modern-js-css-modules-issue)

目前的现象是antd和disableCssModuleExtension这个配置有冲突，我单独使用时两个都没有问题，同时使用时会报错。

我自己推测过，可能和modern.js自动按需加载antd的组件样式有关，但是也尝试过使用@ant-design/pro-card这些pro-components组件，报错信息会指向它们，所以是依赖库里涉及到less语法的可能都有问题？

**Comment by yerled** [comment]
补充一张报错信息的截图，来自上文提到的demo

![image](https://user-images.githubusercontent.com/13483247/156961967-e540c1ac-7980-4b52-ba33-27d939628f5b.png)

**Comment by chenjiahan** [comment]
感谢提供复现 demo~ 我们会在近期继续跟进下

**Comment by yerled** [comment]
我这两天研究了一下loader相关的配置
**css**：
`{
        name: 'css',
        // when disableCssModuleExtension is true,
        // only transfer *.global.css in css-loader
        test: disableCssModuleExtension ? GLOBAL_CSS_REGEX : CSS_REGEX,
        exclude: [CSS_MODULE_REGEX],
      }`
**css-modules**：
`{
        name: 'css-modules',
        test: disableCssModuleExtension ? CSS_REGEX : CSS_MODULE_REGEX,
        exclude: disableCssModuleExtension
          ? [/node_modules/, GLOBAL_CSS_REGEX]
          : [],
        genTSD: this.options.output?.enableCssModuleTSDeclaration,
      }`
所以综合下来，当开启disableCssModuleExtension的时候，node_modules里的样式文件没有匹配到css 相关的loader，所以报错了。
less和sass也是类似的情况。

@chenjiahan

**Comment by chenjiahan** [comment]
感谢反馈~ 这个问题已经在最新版修复咯，相关 PR：https://github.com/modern-js-dev/modern.js/pull/1086
