### ISSUE TITLE
[RFC]: @modern-js/plugin-jarvi 建议

### ISSUE THREAD

**Issue by huxuezhi** [modern-js-dev/modern.js#649]
### 新功能详情

- 升级eslint至v8
- 升级husky至v7
- Eslint 支持vue、angular规则
- 集成@commitlint/cli

**Comment by chenjiahan** [comment]
在之前的变更中，husky 版本从 v7 降级到了 v3：https://github.com/modern-js-dev/modern.js/pull/136

@anc95 能否解释一下更改的原因嘞

**Comment by anc95** [comment]
> @anc95 能否解释一下更改的原因嘞

`ModernJs` 最开始是用内部 Jupiter 开发的，Jupiter 依赖的是 v3 的版本，所以我们项目本身的 husky 配置也是基于 v3 来的，后续做 ModernJs 的 jarvis 插件的时候，我想顺手直接用最新的 husky，不料 3 到 7 间 breaking change 较大，时间原因，就先 downgrade 了，计划后续再升级

**Comment by chenjiahan** [comment]
了解👌🏻

**Comment by chenjiahan** [comment]
Modern.js v2 版本已经升级以上依赖了哈
