### ISSUE TITLE
[RFC]: 引入依赖预打包

### ISSUE THREAD

**Issue by chenjiahan** [modern-js-dev/modern.js#658]
### 新功能详情

依赖预打包有很多好处，比如依赖稳定、安装提速等，参考 umi 的分享：https://mp.weixin.qq.com/s/FTZ93pScf3gykd39voEpng

建议在 `@modern-js/utils` 下新建 `compiled` 或 `prebundled` 目录，存放预打包后的子依赖。

**Comment by leeight** [comment]
之前用esbuild试过，挺难的

**Comment by chenjiahan** [comment]
嗯，直接用 esbuild 是比较困难的，像 require.resolve 这类写法需要单独处理。

目前来看，参考 next.js 和 umi 使用 [ncc](https://github.com/vercel/ncc) 打包，坑会少一些。

**Comment by chenjiahan** [comment]
Closed by https://github.com/modern-js-dev/modern.js/pull/877.
