### ISSUE TITLE
[Bug]: ts类型声明问题

### ISSUE THREAD

**Issue by nightmareT** [modern-js-dev/modern.js#659]
### 版本信息

```sh
@modern-js/app-tools@1.4.0
```

### 问题详情

![image](https://user-images.githubusercontent.com/11377022/155667288-ed419916-7d99-4ed8-b8e1-74191e37dc91.png)
文档中支持bff的配置修改
相应的ts类型声明中缺乏bff的定义 导致tslint失败
interface UserConfig {
  source?: SourceConfig;
  output?: OutputConfig;
  server?: ServerConfig;
  dev?: DevConfig;
  deploy?: DeployConfig;
  tools?: ToolsConfig;
  plugins?: PluginConfig;
  runtime?: RuntimeConfig;
  runtimeByEntries?: RuntimeByEntriesConfig;
}

### 问题复现

无需复现

**Comment by chenjiahan** [comment]
BFF 这个类型是在 `@modern-js/plugin-bff/cli.d.ts` 里扩展声明的，需要在 `modern.config.ts` 中添加 reference 才能正确生效：

```ts
/// <reference types="@modern-js/plugin-bff/cli" />
import { defineConfig } from '@modern-js/app-tools';

export default defineConfig({
  output: {},
  bff: {
    proxy: {},
  },
});
```

可以先临时这么解决，我们再看下是否有更好的方式来使类型定义生效。

**Comment by yimingjfe** [comment]
> ### 版本信息
> ```shell
> @modern-js/app-tools@1.4.0
> ```
> 
> ### 问题详情
> ![image](https://user-images.githubusercontent.com/11377022/155667288-ed419916-7d99-4ed8-b8e1-74191e37dc91.png) 文档中支持bff的配置修改 相应的ts类型声明中缺乏bff的定义 导致tslint失败 interface UserConfig { source?: SourceConfig; output?: OutputConfig; server?: ServerConfig; dev?: DevConfig; deploy?: DeployConfig; tools?: ToolsConfig; plugins?: PluginConfig; runtime?: RuntimeConfig; runtimeByEntries?: RuntimeByEntriesConfig; }
> 
> ### 问题复现
> 无需复现

依赖里有安装 plugin-bff 插件吗，使用 pnpm new 开启 bff 时；会自动引入这部分类型的。

**Comment by chenjiahan** [comment]
@yimingjfe 我试了下好像没有自动生效。

**Comment by nightmareT** [comment]
OK. 我已经按照@chenjiahan 的方案使用了  可以workaround
