### ISSUE TITLE
[Bug]: ToolsConfig  is not support `less` option type

### ISSUE THREAD

**Issue by minjs1cn** [modern-js-dev/modern.js#663]
### 问题详情

![image](https://user-images.githubusercontent.com/75061620/156088048-9d37dfa0-bdee-4a36-be2d-121df4a111f3.png)

不能将类型“{ less: { lessOptions: { javascriptEnabled: true; modifyVars: any; }; }; }”分配给类型“ToolsConfig”。
对象文字可以只指定已知属性，并且“less”不在类型“ToolsConfig”中

### 问题复现

https://codepen.io/minjs1cn/pen/xxPyoeE

**Comment by chenjiahan** [comment]
看了下目前这个类型确实是缺失的，后续会补上。

**Comment by chenjiahan** [comment]
此问题已修复，请升级 `@modern-js/plugin-less` 到 1.2.2 版本，并添加以下 reference 到 `modern.config.ts` 文件的头部：

```ts
/// <reference types="@modern-js/plugin-less" />
```
