### ISSUE TITLE
[Bug]:文档中的assetspath在output的ts定义里面没有，并且想请问一下output.path和output.assetspath区别是什么？ 

### ISSUE THREAD

**Issue by nightmareT** [modern-js-dev/modern.js#670]
### 版本信息

```sh
`-- @modern-js/app-tools@1.4.0  -> /Users/bytedance/bytedance/repos/page-maker-monorepo/common/temp/node_modules/.pnpm/@modern-js+app-tools@1.4.0_typescript@4.5.5/node_modules/@modern-js/app-tools
```

### 问题详情

output中无法定义文档里面https://modernjs.dev/docs/apis/config/output/assets-path
的assetspath
并想请问一下assetspath 和path的区别是什么？

### 复现链接

无需复现

### 复现步骤

moder.config.js直接定义即可

**Comment by chenjiahan** [comment]
app-tools 对应的是 MWA 方案，而 output.assetsPath 只能在模块方案（module-tools）下使用喔。

作用如文档所示：

![image](https://user-images.githubusercontent.com/7237365/156488718-01e5915e-9bbd-45bd-b3d1-e3a18bf36369.png)
