### ISSUE TITLE
[RFC]: 清理未使用的依赖

### ISSUE THREAD

**Issue by chenjiahan** [modern-js-dev/modern.js#677]
### 这个功能解决了什么问题？

目前各个 package 中存在一些未实际使用的 dependencies 和 devDependencies，移除这些依赖可以提升 install speed。

### 你期望的 API 是什么样子的？

无

**Comment by leeight** [comment]
如果有 lint 或者 github actions 限制一下也比较好

**Comment by chenjiahan** [comment]
确实，不过 lint 比较难限制，有一些特殊情况：

- `husky` 这种仅通过安装就能生效的依赖，不存在调用
- 作为 peerDependencies 而被安装的依赖，不存在调用
- linter 难以覆盖的文件类型，比如 sh，json 等

目前我是通过脚本筛查 + 人工判断的方式进行清理，后续看看能否通过 github actions 进行提示。

**Comment by leeight** [comment]
好像有个工具是 `npx scan-deps --directory app,src`

**Comment by chenjiahan** [comment]
试用了下，有一些 bug，不是很稳定，哈哈

**Comment by leeight** [comment]
找 liucheng.leo@bytedance.com，这个是他写的

**Comment by chenjiahan** [comment]
ok👌🏻
