### ISSUE TITLE
[RFC]: `modern.config.js` developer experience optimization

### ISSUE THREAD

**Issue by zoolsher** [modern-js-dev/modern.js#686]
## TS Support

TypeScript support without `///<reference`

## Switch Design
Feature switch should migrate from `package.json plugin install` to `config.[j|t]s`, which would also help debug modern tools. Over depends on `convention over configuration`. 

For example about `BFF`.
```ts
import defineConfig from "@modern-js/app-tools";

export = defineConfig({
    bff: "auto" | true | false | { ...IBffConfiguration }, // default is "auto"
})
```
| value | brief | expiation |
|:--:|:--|:--|
| "auto" | auto attach by `api` folder exists | `api` exists -> enable bff function |
| true | always enabled | `api` not exists -> throw an error |
| false | always disabled | do nothing |

### 你期望的 API 是什么样子的？

// SKIP

**Comment by leeight** [comment]
默认用 modern.config.ts ?

**Comment by zoolsher** [comment]
> 默认用 modern.config.ts ?

absolutely

**Comment by chenjiahan** [comment]
How to make the IBffConfiguration type take effect, do users need to manually import some thing?

**Comment by zoolsher** [comment]
> How to make the IBffConfiguration type take effect, do users need to manually import some thing?

Auto exported by `@modern-js/app-tools`?

**Comment by chenjiahan** [comment]
`plugin-bff` is an optional plugin, and cannot be declared as a dependency of `@modern-js/app-tools`.

The following config should be more type friendly:

```ts
import defineConfig from "@modern-js/app-tools";
import bff from '@modern-js/plugin-bff'

export = defineConfig({
  plugins: [
    bff({
      ...IBffConfiguration
    })
  ],
})
```
