### ISSUE TITLE
[Bug]: 创建”生成器插件“类型的模块项目时报错

### ISSUE THREAD

**Issue by yerled** [modern-js-dev/modern.js#715]
### 版本信息

```sh
/Users/yerled/Documents/workspace
└── (empty)




在创建项目时报错，还未进入项目内
```

### 问题详情

按照官方文档，尝试[开发生成器插件](https://modernjs.dev/docs/guides/features/custom/generator-plugin/develop)，但失败了。

![image](https://user-images.githubusercontent.com/13483247/157799968-b5b065ab-5bab-469f-ba1c-fa6df52f7abb.png)

### 复现链接

🈚️

### 复现步骤

1. npx @modern-js/create plugin --plugin @modern-js/generator-plugin-plugin
2. 工程类型选择 “模块”
3. 项目场景选择 “生成器插件”
4. 控制台报错

**Comment by chenjiahan** [comment]
这个包已经重新发布了，麻烦再试下喔
