### ISSUE TITLE
[Bug]: modern dev electron --entry 参数失效

### ISSUE THREAD

**Issue by faxinwang** [modern-js-dev/modern.js#723]
### 版本信息

```sh
test@0.1.0 D:\proj\test
`-- @modern-js/app-tools@1.4.3
```

### 问题详情

把如下的包从
"@modern-js/runtime": "^1.0.0",
"@modern-js/app-tools": "^1.0.0",
"@modern-js/plugin-electron": "^1.0.0",
升级到
"@modern-js/runtime": "^1.2.3",
"@modern-js/app-tools": "^1.4.3",
"@modern-js/plugin-electron": "^1.0.15",
之后，`modern dev electron` 命令的 `--entry` 参数就失效了，目前在
`node_modules\@modern-js\electron-tools\dist\js\node\utils\paths.js`文件中通过修改`DEFAULT_ELECTRON_MAIN_FOLDER`的初始值能够临时解决问题。

### 复现链接

无

### 复现步骤

无

**Comment by spcBackToLife** [comment]
this has fixed in: https://github.com/modern-js-dev/electron-sprout/pull/109,
and will publish soon.

**Comment by faxinwang** [comment]
最近更新了两次依赖包，这个问题还是存在，我目前的依赖版本是：
```
"@modern-js/runtime": "^1.3.1",
"@modern-js/app-tools": "^1.6.5",
"@modern-js/plugin-electron": "^1.0.19",
"@modern-js/plugin-jarvis": "^1.2.12",
```

**Comment by chenjiahan** [comment]
由于 Modern.js 整体规划调整，从 Modern.js 2.0 版本开始，将不再提供 Electron 工程方案，且 Modern.js v1 的 Electron 工程方案也不再进行新的迭代。

因此，Electron 相关 issue 将被关闭。如果有相关需求，欢迎 fork Modern.js Electron 相关代码进行二次开发，感谢理解~
