### ISSUE TITLE
[Bug]: Git clone failed on win10

### ISSUE THREAD

**Issue by ahaoboy** [modern-js-dev/modern.js#754]
### Version

```sh
git version 2.35.1.windows.2
```

### Details

 git clone https://github.com/modern-js-dev/modern.js.git
Cloning into 'modern.js'...
remote: Enumerating objects: 43647, done.
remote: Counting objects: 100% (6045/6045), done.
remote: Compressing objects: 100% (1143/1143), done.
remote: Total 43647 (delta 2730), reused 5623 (delta 2443), pack-reused 37602
Receiving objects: 100% (43647/43647), 27.62 MiB | 1.80 MiB/s, done.
Resolving deltas: 100% (28518/28518), done.
error: unable to create file packages/cli/plugin-analyze/tests/fixtures/entries/file-system-routes/_node_modules/.modern-js/main/internal_components/Comp___modern_js_internal_pages_a_b_about_ts___modern_js_internal_pages_a_b__layout_ts___modern_js_internal_pages_a__layout_ts.jsx: Filename too long
error: unable to create file packages/cli/plugin-analyze/tests/fixtures/entries/file-system-routes/_node_modules/.modern-js/main/internal_components/Comp___modern_js_internal_pages_a_b_index_ts___modern_js_internal_pages_a_b__layout_ts___modern_js_internal_pages_a__layout_ts.jsx: Filename too long
error: unable to create file packages/cli/plugin-analyze/tests/fixtures/entries/file-system-routes/_node_modules/.modern-js/main/internal_components/Comp___modern_js_internal_pages_a_b_info_ts___modern_js_internal_pages_a_b__layout_ts___modern_js_internal_pages_a__layout_ts.jsx: Filename too long
Updating files: 100% (3381/3381), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

### Reproduce link

https://github.com/modern-js-dev/modern.js.git

### Reproduce Steps

execute `git clone https://github.com/modern-js-dev/modern.js.git`

**Comment by chenjiahan** [comment]
We will rename these files to avoid this issue.

**Comment by chenjiahan** [comment]
You can fix this by `git config --system core.longpaths true`
