### ISSUE TITLE
[Bug]: File '@modern-js/tsconfig/base' not found

### ISSUE THREAD

**Issue by bvanjoi** [modern-js-dev/modern.js#763]
### Version

```sh
`@modern-js/create: 1.3.1`
```

### Details

`@modern-js/tsconfig`  is not included in `devDependencies`

<img width="675" alt="image" src="https://user-images.githubusercontent.com/30187863/159218808-610dc282-dd41-4bcc-b3a0-c4f1fa733d47.png">

### Reproduce link

NOT_NEED

### Reproduce Steps

execute `npx @modern-js/create test`

**Comment by caohuilin** [comment]
重新装一下依赖试一下

**Comment by bvanjoi** [comment]
> 重新装一下依赖试一下

明白！但我感觉模版内应该带上这个依赖会更好些。

**Comment by caohuilin** [comment]
这个依赖现在是个隐式依赖，在 pnpm 场景下放到了 npmrc 的 hoist 中了，monorepo 场景下确实可能会有问题，已经在重新设计这块的依赖逻辑了，后续会有新的设计方案。
