### ISSUE TITLE
[Bug]: 使用微前端插件，主应用加载子应用资源时跨域错误

### ISSUE THREAD

**Issue by yerled** [modern-js-dev/modern.js#772]
### 版本信息

```sh
monorepo@ /Users/yerled/Documents/yuanguanglong/whale2
└── (empty)
```

### 问题详情

主子应用都是基于modern-js搭建，并开启微前端。主应用加载子应用资源时报跨域错误

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/13483247/159429867-40f7fab6-d40e-426f-bf96-bbc4acaa2386.png">

### 复现链接

https://github.com/yerled/modern-js-issue-plugin-garfish

### 复现步骤

启动主子应用

打开主应用界面

控制台报跨域错误。

**Comment by zhoushaw** [comment]
按照： https://modernjs.dev/docs/apis/config/tools/dev-server
配置了，也不可以是嘛：
```js
devServer: {
    headers: {
      // 保证子应用的资源支持跨域，在上线后需要保证子应用的资源在主应用的环境中加载不会存在跨域问题（**也需要限制范围注意安全问题**）
      'Access-Control-Allow-Origin': '*',
    },
  },
```

**Comment by yerled** [comment]
尝试配置了tools.devServer，或者通过webpackChain修改，两种方案都不生效。
![image](https://user-images.githubusercontent.com/13483247/159443901-612de3cc-1b2a-4b07-b2a4-df88cc473aa2.png)
