### ISSUE TITLE
[Bug]: npx @modern-js/create website

### ISSUE THREAD

**Issue by WGSHUHU** [modern-js-dev/modern.js#843]
### Version

```sh
无
```

### Details

直接使用npx @modern-js/create website，生成项目，运行yarn dev，直接报错

### Reproduce link

无

### Reproduce Steps

无

**Comment by chenjiahan** [comment]
![image](https://user-images.githubusercontent.com/7237365/161029666-a9942391-4192-4f9c-ad93-b20998cc0e2c.png)

我试了下可以正常运行，能提供一下具体的复现步骤、复现截图和操作系统吗

**Comment by chenjiahan** [comment]
我这边可以正常运行，你能把报错截个图看下吗

**Comment by WGSHUHU** [comment]
我重新全局安装了一下 @modern-js/create，然后就好了

**Comment by caohuilin** [comment]
> 我重新全局安装了一下 @modern-js/create，然后就好了

建议不要全局安装，使用npx的方式创建项目，每次都是拉最新的

**Comment by WGSHUHU** [comment]
> 
![screenshot-20220401-175024](https://user-images.githubusercontent.com/32232228/161240222-ff746b62-350c-462b-8c30-40ae6bedf896.png)

**Comment by chenjiahan** [comment]
@WGSHUHU 是重新安装后还有其他问题吗

**Comment by chenjiahan** [comment]
看到你新开了一个 issue：https://github.com/modern-js-dev/modern.js/issues/853

这个先 close 了
