### ISSUE TITLE
[RFC]: 增加 upgrade 命令来自动化依赖包的升级

### ISSUE THREAD

**Issue by faxinwang** [modern-js-dev/modern.js#850]
### 这个功能解决了什么问题？

像 quasar framework 那样，添加一个 upgrade 子命令，自动检测和升级可以升级的npm包。

### 你期望的 API 是什么样子的？

modern upgrade 显示所有可以升级的顶层包

modern upgrade -i 安装所有可以升级的顶层宝

**Comment by chenjiahan** [comment]
感谢建议，我们后续会评估下是否支持该命令。

**Comment by chenjiahan** [comment]
@caohuilin 看看是不是可以作为生成器的能力~

**Comment by caohuilin** [comment]
> @caohuilin 看看是不是可以作为生成器的能力~

生成器可以帮忙升级和安装依赖，自动检测感觉可以写一个单独的插件实现，去调用生成器的能力

**Comment by caohuilin** [comment]
https://modernjs.dev/docs/apis/app/commands/upgrade
