### ISSUE TITLE
[Bug]: yarn dev报错

### ISSUE THREAD

**Issue by WGSHUHU** [modern-js-dev/modern.js#853]
### Version

```sh
middle-platform@0.1.0
  └── @modern-js/app-tools@1.3.2
```

### Details

![screenshot-20220401-181142](https://user-images.githubusercontent.com/32232228/161243715-6a459e4b-441c-4622-9cbb-c88ce85cbfab.png)

### Reproduce link

无

### Reproduce Steps

无

**Comment by WGSHUHU** [comment]
window平台

**Comment by chenjiahan** [comment]
你的 app-tools 版本不是最新的，可以先升级到 1.4.5 试一下喔
