### ISSUE TITLE
[RFC]: pnpm run new安装的插件如何删除或更换

### ISSUE THREAD

**Issue by Andyspace5** [modern-js-dev/modern.js#858]
### 这个功能解决了什么问题？

比如我BFF装了 koa 但是想换成 egg该如何操作？

### 你期望的 API 是什么样子的？

可以 remove 然后 重新run. new 安装选项

**Comment by chenjiahan** [comment]
1. 移除相关依赖

```bash
yarn remove @modern-js/plugin-koa @modern-js/plugin-bff koa @types/koa
```

2. 删除 modern-app-env.d.ts 中的 reference

```ts
/// <reference types='@modern-js/plugin-koa/types' />
```

3. 移除 api 目录下 koa 相关代码

4. 重新调用生成器，选择 egg 框架

```
yarn new
```
