### ISSUE TITLE
[Bug]: tools.tailwindcss 漏掉了类型定义

### ISSUE THREAD

**Issue by faxinwang** [modern-js-dev/modern.js#861]
### 版本信息

```sh
@modern-js/app-tools@1.4.5
```

### 问题详情

用从 `@modern-js/app-tools` 中导出的 `defineConfig` 定义配置时，在 `tools` 下面定义 `tailwindcss` 会报错，点开对应的 .d.ts 文件发现确实漏掉了 `tailwindcss` 配置项的定义，具体位置在 `@modern-js/core/dist/types/config/index.d.ts` 的 `ToolsConfig` 里面。

我的 `@modern-js/core` 版本是 1.6.0 

> 

### 复现链接

无

### 复现步骤

无

**Comment by chenjiahan** [comment]
已在最新版本修复 config 类型问题，可以升级试下
