### ISSUE TITLE
[Bug]: config `disableSourceMap` is actually `enableSourceMap` in module-tools

### ISSUE THREAD

**Issue by Means88** [modern-js-dev/modern.js#878]
### Version

```sh
@modern-js/module-tools@1.4.2
```

### Details

https://modernjs.dev/docs/apis/config/output/disable-source-map

```ts
import { defineConfig } from '@modern-js/app-tools';

export default defineConfig({
  output: {
    disableSourceMap: true,
  },
});
```

https://github.com/modern-js-dev/modern.js/blob/0a4f27f043b8884f0f12b904b3d5886bb4aa966d/packages/solutions/module-tools/src/features/build/utils.ts#L105

### Reproduce link

noop

### Reproduce Steps

1. create a module project
2. set `disableSourceMap: false` in modern.config.js
3. `yarn build`
4. no source map

**Comment by chenjiahan** [comment]
在 module-tools 2.x 版本中已经重新设计了 config，不再有此问题。

相关文档：https://modernjs.dev/module-tools/api/index.html
